### ISSUE TITLE
Events with extra keys not being caught by RunEngine

### ISSUE THREAD

**Issue by jrmlhermitte** [bluesky/bluesky#1009]
In the data, I found the following (on SIX beamline,  @awalter-bnl had this issue)
```py3
hdr = db[11417]
stream = hdr.documents('baseline')
next(stream)
desc = next(stream)

Out[48]: False
In [47]: next(streams)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-47-0b15355aa0e2> in <module>()
...
KeyError: 'm3diag_location'

In [48]: "m3diag_location" in desc[1]['data_keys'].keys()
Out[48]: False


```

What is happening here is that an ophyd object was defined with a `obj.read()` attribute that returned keys that didn't match `obj.describe()`. Somehow this went through without the RunEngine complaining.
(see [here](https://github.com/NSLS-II-SIX/profile_collection/blob/7d6609789a57bddcfda65e58ea7f2757a9a8ee20/startup/11-diagnostic.py#L48) )
Should we check for this?

I will try to come back to this issue and clean up/edit when i have more time.
@tacaswell may have some ideas on this

**Comment by tacaswell** [comment]
This was an intentional (but possibly premature) decision to not validate every event document on the way out.

**Comment by tacaswell** [comment]
On further consideration, we should check when we construct the descriptor that it matches what is returned from read.
