### ISSUE TITLE
improve how we interact with the asyncio event loop

### ISSUE THREAD

**Issue by tacaswell** [bluesky/bluesky#1062]
We currently start/stop the asyncio event loop in `__call__` and `resume` which is at best rude and at worst bad-practice.   This prevents us from running the RE inside of jupyter with tornado >= 5.  

This is a sketch of a path to using a running event loop and still getting the blocking behavior we need it `__call__`.  In the IPython case we will need to spawn a event loop on a background thread and then start it, in the case of jupyter we will have to bind the existing loop to the RE and use that. 

This also solves the problem of how we use `caproto.asyncio` with the RE (as it also just uses the background loop for the monitors)  

The kicker integration will need to move into `__call__` but I think I see a path to that that will end up being better anyway (basically re-use the logic that ipython already does it to start the event loop and then kill it on cue).  I suspect this will also fix the issue of open the modal window pausing the scan!

```python
import asyncio
import threading

loop = asyncio.new_event_loop()

def runner():
    loop.run_forever()

th = threading.Thread(target=runner)
th.start()

async def sleepy_worker(n):
    for j in range(n):
        print(f'sleeping loop {j} of {n}')
        await asyncio.sleep(1)
    return n

def sync_worker2(n):
    print('about to create task')    
    h = asyncio.run_coroutine_threadsafe(sleepy_worker(n), loop=loop)
    print('created task')        
    h.add_done_callback(lambda _: print('finished, kill kicker here'))
    if not h.done():
        # start kicker
        # qt_event_loop.exec_()
        pass
    print('about to waiting')
    return h.result()
    print('done waiting')


# sync_worker2(5)

```

**Comment by tacaswell** [comment]
sometimes....

**Comment by danielballan** [comment]
> This also solves the problem of how we use `caproto.asyncio` with the RE (as it also just uses the background loop for the monitors)

Is this referring to a vaporware asyncio client?

**Comment by klauer** [comment]
It probably wasn't vaporware back in June!

**Comment by danielballan** [comment]
You lost me.

**Comment by klauer** [comment]
This PR is from June. Our status/vision/thoughts/etc. about caproto were drastically different back then.

**Comment by danielballan** [comment]
Ah I see. @tacaswell was (in other channels) asserting that we had written an asyncio client. He was probably thinking of the asyncio _repeater_ or "autocompleting from curio and trio to asyncio" in his words. :- D
