### ISSUE TITLE
NFS/BS interaction?

### ISSUE THREAD

**Issue by cmazzoli** [bluesky/bluesky#1073]
Title per @tacaswell
Bug report created to leave a note/memory of what happened several times in the last days...
Moreover BS was irresponsive on the scale of tens of minutes to command, one of which was:
RE(mv(fccd.exposure, (...)))
hitting an IOC showing excellent health in principle

````
|        47 | 15:36:10.1 |      1.042 |           1017364 |             13374 |                                                                                                                     
|        48 | 15:36:16.5 |      1.044 |            748227 |              9752 |                                                                                                                     
|        49 | 15:36:22.9 |      1.046 |           1204222 |             15647 |                                                                                                                     
+-----------+------------+------------+-------------------+-------------------+                                                                                                                     
|   seq_num |       time |   tardis_l | fccd_stats1_total | fccd_stats3_total |
+-----------+------------+------------+-------------------+-------------------+
|        50 | 15:36:29.3 |      1.048 |            979430 |             13736 |
|        51 | 15:36:35.7 |      1.050 |           1056980 |             14210 |                                                                                                                     
+-----------+------------+------------+-------------------+-------------------+
generator rel_scan ['7d36f7b7'] (scan num: 105540)
Out[33]: ('7d36f7b7-0377-4df4-90dd-bed0a502ea04',)                                                                                                                                                  

In [34]: RE(mv(fccd.exposure, (1,0,10)))
The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database',)).History will not be written to the database.
Traceback (most recent call last):
  File "/opt/conda_envs/collection-2018-1.0.1/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/IPython/__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 480, in mainloop
    self.interact()
  File "/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 471, in interact
    self.run_cell(code, store_history=True)
  File "/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2675, in run_cell
    self.logger.log(cell, raw_cell)
  File "/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/IPython/core/logger.py", line 185, in log
    self.log_write(line_mod)
  File "/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/IPython/core/logger.py", line 201, in log_write
    self.logfile.flush()
OSError: [Errno 116] Stale file handle

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/conda_envs/collection-2018-1.0.1/lib/python3.6/site-packages/IPython/core/history.py", line 578, in end_session
    len(self.input_hist_parsed)-1, self.session_number))
sqlite3.OperationalError: attempt to write a readonly database
[xf23id1@xf23id-ws3 ~/Users/2018/2018_07_CMP]$ 


````

**Comment by CJ-Wright** [comment]
We had a similar issue at XPD. It turns out the GPFS had fallen over at the time.

**Comment by cowanml** [comment]
On Wed, 25 Jul 2018, Christopher J. Wright wrote:
> We had a similar issue at XPD. It turns out the GPFS had fallen over at the time.

The beamline's local gpfs or central gpfs via cnfs (eg. central homedirs, etc)?

**Comment by tacaswell** [comment]
We would have to check with @cmazzoli as to where their profiles are stored.

**Comment by danielballan** [comment]
ping @cmazzoli -- Can you remind us where the profiles are actually stored on disk? I recall there is at least one layer of dereferencing via soft-links.

**Comment by cowanml** [comment]
On Mon, 30 Jul 2018, Dan Allan wrote:
> ping @cmazzoli -- Can you remind us where the profiles are actually stored on disk? I recall
> there is at least one layer of dereferencing via soft-links.

*1* layer!?!


----------------------------------------------------------------------
# 1st filesystem, xf23id1 homedir on local beamline gpfs

# note inconsistent symlink targets.

# collection, arguably the most important, actually goes through a
# whole extra layer of indirection involving an additional mountpoint
# and symlink that until recently was on a whole other filesystem
# mounted from a different server.

[xf23id1@xf23id-ws3 ~]$ ls -al .ipython
total 256K 
drwxr-xr-x   7 xf23id1 4.0K Apr  4 18:44 .
drwxr-xr-x 107 xf23id1 128K Jul 30 17:12 ..
drwxr-xr-x   2 xf23id1 4.0K Dec 12  2014 extensions
drwxr-xr-x   2 xf23id1 4.0K Dec 12  2014 nbextensions
drwxrwxr-x   5 xf23id1 4.0K Oct  6  2015 old_profiles
lrwxrwxrwx   1 xf23id1   41 Sep 24  2015 profile_collection -> /epics/xf/23id/ipython/profile_collection 
drwxr-xr-x   8 xf23id1 4.0K Oct  7  2016 profile_default
drwxr-xr-x   8 xf23id1 4.0K Oct  7  2016 profile_default_old
lrwxrwxrwx   1 xf23id1   59 Jan 30 15:29 profile_simulated -> /home/xf23id1/xf23id1_profiles_simulated/profile_simulated/
-rw-r--r--   1 xf23id1  100 Dec 11  2014 README

[xf23id1@xf23id-ws3 ~]$ df .
Filesystem        1K-blocks         Used    Available Use% Mounted on
xf23id         298370203648 104024309760 194345893888  35% /home/xf23id1


# 2nd filesystem, /direct/xf23id  (now also on local beamline gpfs)

[xf23id1@xf23id-ws3 ~]$ cd /epics/xf/23id
[xf23id1@xf23id-ws3 /epics/xf/23id]$ df .
Filesystem        1K-blocks         Used    Available Use% Mounted on
xf23id         298370203648 104024309760 194345893888  35% /direct/xf23id


# and those that are symlinks actually circle around back into
# /home/xf23id1 again!?!

# I presume *all* of this is vestigial leftovers from having local
# homedirs for the xf23id1 account at one point?  Can't think of any
# good reason to keep it that way.

[xf23id1@xf23id-ws3 /epics/xf/23id]$ ls -al ipython/
total 256K 
drwxrwsrwx 30 xf23id1 4.0K Apr  4 18:47 .
drwxrwxr-x  9 root    4.0K Jul 25 00:17 ..
drwxrwsr-x  4 xf23id1 4.0K Sep 24  2015 asdf
drwxr-sr-x  8 xf23id1 4.0K Mar  5  2016 backup_profile_collection
-rw-r--r--  1 xf23id1  40K Jan 13  2016 descriptor_recovery.ipynb
drwxr-sr-x  2 xf23id1 4.0K Dec 17  2014 extensions
drwxr-sr-x  8 xf23id1 4.0K Jan 30 16:58 .git
-rw-r--r--  1 xf23id1  753 Jan 25  2015 .gitignore
-rw-r--r--  1 xf23id1 1.3K Jan 25  2015 LICENSE
drwxr-sr-x  2 xf23id1 4.0K Dec 17  2014 nbextensions
drwxr-sr-x  3 xf23id1 4.0K Mar 11  2015 profile_
lrwxrwxrwx  1 xf23id1   57 May  2 10:32 profile_analysis -> /home/xf23id1/xf23id1_profiles_analysis/profile_analysis/
drwxrwsr-x  7 xf23id1 4.0K Aug  4  2015 profile_asdf
lrwxrwxrwx  1 xf23id1   50 May  2 10:32 profile_collection -> /home/xf23id1/xf23id1_profiles/profile_collection/ 
drwxr-sr-x  7 xf23id1 4.0K Oct  7  2015 profile_collection-stable
drwxrwsr-x  8 xf23id1 4.0K Nov 11  2015 profile_debug-wait
drwxrwsr-x  8 xf23id1 4.0K Jun 12 15:17 profile_default
drwxrwsr-x  8 xf23id1 4.0K Apr  4 18:44 profile_default_old
drwxr-sr-x  7 xf23id1 4.0K Mar 20 22:20 profile_deleteme
drwxr-xr-x  8 xf23id1 4.0K Oct  1  2015 profile_demo
drwxr-sr-x  8 xf23id1 4.0K Jun 25  2015 profile_jibberish
drwxr-sr-x  8 xf23id1 4.0K Jun 25  2015 profile_jibboaeu
drwxrwsr-x  8 xf23id1 4.0K Jun 26  2015 profile_junk
drwxr-sr-x  7 xf23id1 4.0K Jun 20  2016 profile_notebook
drwxrwsr-x  8 xf23id1 4.0K Apr 28  2015 profile_ophyd
drwxr-sr-x  7 xf23id1 4.0K Oct  5  2015 profile_profile_xf23id1_bs
lrwxrwxrwx  1 xf23id1   59 May  2 10:32 profile_simulated -> /home/xf23id1/xf23id1_profiles_simulated/profile_simulated/
drwxrwsr-x  8 xf23id1 4.0K Apr 10  2017 profile_test_analysis
drwxr-sr-x  7 xf23id1 4.0K Oct 21  2016 profile_test-analysis2
drwxr-sr-x  8 xf23id1 4.0K Feb 12  2015 profile_xf23id
drwxrwsrwx  9 xf23id1 4.0K Jul 24  2015 profile_xf23id1
drwxr-sr-x  8 xf23id1 4.0K Apr 25  2015 profile_=xf23id1
drwxrwsr-x 10 xf23id1 4.0K Oct  6  2015 profile_xf23id1_bs
drwxr-sr-x  8 xf23id1 4.0K Sep  9  2015 profile_xf23id1-bs
drwxr-sr-x 11 xf23id2 4.0K Mar  3  2016 profile_xf23id2
lrwxrwxrwx  1 xf23id2   49 May  2 10:32 profile_xf23id2bs -> /home/xf23id2/xf23id2_profiles/profile_xf23id2bs/ 
drwxrwsr-x 11 xf23id2 4.0K Apr 25  2017 profile_xf23idbs
-rw-r--r--  1 xf23id1  195 Dec 17  2014 README
-rw-r--r--  1 xf23id1   16 Jan 25  2015 README.md
-rw-r--r--  1 xf23id1 8.0K Jul  5  2017 test-trash.sqlite


[xf23id1@xf23id-ws3 /epics/xf/23id]$ cd /home/xf23id
/home/xf23id1

[xf23id1@xf23id-ws3 ~]$ ls -ald xf23id1_profiles*
drwxrwxr-x 4 xf23id1 4.0K Apr  4 15:16 xf23id1_profiles
drwxrwxr-x 4 xf23id1 4.0K Jan 30 18:15 xf23id1_profiles_analysis
drwxrwxr-x 4 xf23id1 4.0K Jan 30 17:26 xf23id1_profiles_simulated

# someone just really went gonzo with the symlinks?

[xf23id1@xf23id-ws3 ~]$ ls -al xf23id1_profiles
total 256K 
drwxrwxr-x   4 xf23id1 4.0K Apr  4 15:16 .
drwxr-xr-x 107 xf23id1 128K Jul 30 17:12 ..
drwxrwxr-x   8 xf23id1 4.0K May 29 17:24 .git
-rw-rw-r--   1 xf23id1 1.6K Jan 10  2018 .gitignore
lrwxrwxrwx   1 xf23id1   56 Apr  4 15:16 profile_analysis -> /home/xf23id1/xf23id1_profiles_analysis/profile_analysis
drwxrwxr-x  10 xf23id1 4.0K Jul 29 16:22 profile_collection
lrwxrwxrwx   1 xf23id1   59 Apr  4 15:16 profile_simulated -> /home/xf23id1/xf23id1_profiles_simulated/profile_simulated/


[xf23id1@xf23id-ws3 ~]$ ls -al xf23id1_profiles/profile_collection/
total 3.0M 
drwxrwxr-x 10 xf23id1 4.0K Jul 29 16:22 .
drwxrwxr-x  4 xf23id1 4.0K Apr  4 15:16 ..
drwxrwxr-x  2 xf23id1 4.0K Jul 20  2017 acceptance_tests
drwxrwxr-x  2 xf23id1 4.0K Jan 17  2017 db
-rw-rw-r--  1 xf23id1   40 Jul 20  2017 .gitignore
-rw-r--r--  1 xf23id1 2.5M Jul 29 16:22 history.sqlite
-rw-rw-r--  1 xf23id1  20K Mar  5  2016 ipython_config.py
-rw-rw-r--  1 xf23id1  32K Mar  5  2016 ipython_nbconvert_config.py
-rw-rw-r--  1 xf23id1  25K Mar  5  2016 ipython_notebook_config.py
-rw-rw-r--  1 xf23id1  25K Mar  5  2016 ipython_qtconsole_config.py
drwxrwxr-x  2 xf23id1 4.0K Mar  5  2016 log
drwxrwxr-x  2 xf23id1 4.0K Jan 10  2018 nuke
drwx------  2 xf23id1 4.0K Mar  5  2016 pid
drwx------  2 xf23id1 4.0K Jan 17  2017 security
drwxrwxr-x  3 xf23id1 4.0K May  4 10:17 startup
drwxrwxr-x  3 xf23id1 4.0K Mar  5  2016 static
----------------------------------------------------------------------

**Comment by tacaswell** [comment]
Closing as a NSLS-II infrastructure specific problem, @cmazzoli In the future can you please report this sort of thing via TRAC.
