### ISSUE TITLE
ENH add transient key to keep up with incremented scan_id for print_summary.

### ISSUE THREAD

**Issue by ambarb** [bluesky/bluesky#1075]
@awalter-bnl can provide some background as he brought this trick with him to print out more information specific to the scan at the end of a completed RunEngine plan.

I added to make the md string be the same and to be mutable based on the motor setpoints.  Now users want to understand in advance what the scan numbers will be (not everyone is comfortable with md strings (and we can also make a mistake with this so this feature could help.)

The output of the print_summary current looks exactly like what we see for the RunEngine, but it doesn't keep track of the alignment scans so it isn't necessary simple math to predict the scan_id

```
scan no 21720 sample 3 A - E = 853.0eV - Pol V
scan no 21720 sample 3 A - E = 853.2eV - Pol V
scan no 21720 sample 3 A - E = 853.4eV - Pol V
scan no 21720 sample 3 A - E = 853.6eV - Pol V
scan no 21720 sample 3 A - E = 853.8eV - Pol V
scan no 21720 sample 3 A - E = 854.0eV - Pol V
scan no 21720 sample 3 A - E = 854.2eV - Pol V
scan no 21720 sample 3 A - E = 854.4eV - Pol V
scan no 21720 sample 3 A - E = 854.6eV - Pol V
scan no 21720 sample 3 A - E = 854.8eV - Pol V
scan no 21720 sample 3 A - E = 855.0eV - Pol V
scan no 21720 sample 3 A - E = 855.2eV - Pol V
scan no 21720 sample 3 A - E = 855.4eV - Pol V
scan no 21720 sample 3 A - E = 855.6eV - Pol V
scan no 21720 sample 3 A - E = 855.8eV - Pol V
scan no 21720 sample 3 A - E = 856.0eV - Pol V
scan no 21720:  dark 
scan no 21720:  dark 



 EXAMPLE METADATA FOR SCAN:
         sample 3 A - E = 856.0eV - Pol V

```

**Comment by awalter-bnl** [comment]
Hi Andi,
I will stop by on Monday to take a look at this, in principle it isn't possible to know the scan_id ahead of time. The trick I used is to look at the last scan_id and increase it by 1. I will have to look at your exact plan system to work out how to get each scan_id to increase further.

cheers
Andrew

**Comment by ambarb** [comment]
Hi Andrew
Thanks,  I was trying to do that and it works okay as long as you don't change the plan. Right now we have to align m1 and m3 so that is an additional complication, plus any dummy image etc.  If we slightl alter the plan or chain it together with multiple instances, it gets really complicated very quickly.  This is why I hope print_summary could have a specific key for this.
Thanks for volunteering to look into it.  WE have users until Tuesday morning (or maybe Wednesday morning)

**Comment by awalter-bnl** [comment]
So I have thought about this a little more, and am not sure we can modify print_summary (or summarise_plan as it is now known) to give exactly what you want @ambarb. We should discuss, I am sure that I can print an 'expected scan_id' for all internal 'runs' but the other info like `sample 3 A - E = 853.0eV - Pol V` is very specific to the type of scan you are running and can't be genralized to work for all possible plans.

**Comment by ambarb** [comment]
YEs, it cannot be generalized.  That was why I was asking if DAMA can make a key for summarize_print() so that we can use this more as a simulation engine and less of a code/math checker.  @danielballan already added checking of limits.

**Comment by awalter-bnl** [comment]
This is a bit more specialized than checking limits, I will need to think about how to structure this as well. It is pretty easy to look for messages associated with moving and check that this is within the limits. It is impossible to tell if they are within a `for loop` as that info doesn't make it's way down to the messages outputted by the plan generator (which we use for `summarize_plans` etc.). In principle I could include separate lines for each 'move', similar to what `summarize_plans` does but limit it to only `moves` that occur between runs but this might produce to much info. We should have a one-one discussion to work out a solution that suits what you want and is technically possible.

**Comment by awalter-bnl** [comment]
This issue has been addressed in [NSLS-II/sixtools PR # 32](https://github.com/NSLS-II-SIX/sixtools/pull/32)

**Comment by mrakitin** [comment]
Resolved in sixtools.
