### ISSUE TITLE
08 - Simple Compound Device.ipynb import error

### ISSUE THREAD

**Issue by robmarkcole** [bluesky/bluesky#1082]
On https://try.nsls2.bnl.gov the notebook `08 - Simple Compound Device.ipynb` has the import error:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-12-c4e47e0fd08a> in <module>()
----> 1 from bluesky.plans import outer_product_scan, subs_wrapper
      2 
      3 # Define a simulated detector that is coupled to our simulated XY stage.
      4 det = Syn2DGauss('det',
      5                  stage.x, 'stage_x',

ImportError: cannot import name 'subs_wrapper'
```

**Comment by danielballan** [comment]
Good to hear. You _might_ also be interested in our caproto project: https://nsls-ii.github.io/caproto/ It lets you use Python all the way to integrating with the device driver. Be advised that it's a less mature project than bluesky/ophyd, and we're still finding some important bugs from time to time.
