### ISSUE TITLE
Add info on jupyter kernel

### ISSUE THREAD

**Issue by robmarkcole** [bluesky/bluesky#1085]
This is not an issue but a suggestion you could add to your [Before you begin](http://nsls-ii.github.io/bluesky/tutorial.html#before-you-begin) tutorial a brief [instruction ](https://anbasile.github.io/programming/2017/06/25/jupyter-venv/) on creating a Bluesky kernel that can be used with Jupyter notebooks:
```
(bluesky-tutorial) : ipython kernel install --user --name=bluesky
```

**Comment by danielballan** [comment]
Let's leave this issue open and circle back to it once Jupyter and matplotlib play nicer together. When everything goes well this can work just fine --- as it does on the try.nsls2.bnl.gov deployment --- but users trying this on their own machines are likely to hit pitfalls such as those reported in #1087. And the new JupyterLab only makes it more complicated. I happen to be working on this issues from the Jupyter side, so I'll circle back here once I think it's less of a minefield. For now, I would just recommend that users stick to classic `ipython` per the tutorial.

**Comment by danielballan** [comment]
Blocked by event loop refactor, still worth doing.
