### ISSUE TITLE
Simplify zmq--asyncio event loop integration

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky#1108]
The test suite generates warnings that suggest we can simplify things due to changes in pyzmq:

```
/home/dallan/Repos/bnl/bluesky/bluesky/callbacks/zmq.py:236: DeprecationWarning: ZMQEventLoop and zmq.asyncio.install are deprecated in pyzmq 17. Special eventloop integration is no longer needed.
  loop = zmq_asyncio.ZMQEventLoop()

```

**Comment by tacaswell** [comment]
Could this be related to the 3.7 failures in https://github.com/NSLS-II/bluesky/pull/1063 ?

**Comment by danielballan** [comment]
Unsure.

More info on the deprecation is in the first "Note" box on this page: https://pyzmq.readthedocs.io/en/latest/eventloop.html

**Comment by stan-dot** [comment]
closing as the error is no longer experienced
