### ISSUE TITLE
Is there a place we could call pyplot.ion() safely?

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky#1126]
It would be nice if we could do this for the user to minimize the bluesky "hello world" code, but we should only do it if (1) there is a clear way to override it and (2) we can do it in a context where the user has signaled that they want interactive plots. For example, `import bluesky` should certainly not affect the state of `pyplot.ion()/ioff()`. But maybe using `LivePlot(...)` could.

**Comment by tacaswell** [comment]
I am concerned that there is no "safe" place to do this that will not eventually be surprising or confusing.

As we move towards GUIs for interactive viz and / or more helper scripts to do the actually RE initialization, we can pass on putting this someplace in the bluesky codebase.
