### ISSUE TITLE
Watch memory usage during a 500,000-point scan.

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky#1136]
User report:

> [At CMS we] started a continuous exposures (one after the other in the speed of 2-3s/image) for Pilatus2M. The exposure lasted about 8 days and generated about 500,000 images. After this long exposures, the system became very slow and showed a high resource usage of bluesky (76% memory). It remained slow even after killing the ipython process by command 'kill -9'. The workstation has to be restarted.

This could be a caproto issue, but I figure we'll start with bluesky + ophyd.sim and start making this more realistic until we can reproduce the leak.

Reported as ticket 2901 in NSLS-II Trac.

**Comment by tacaswell** [comment]
I suspect that the slowness was stuff got pushed to swap and it would have recovered eventually without a restart.

Do we have anymore information about what the plan they were running was?  How much RAM did the machine have (75% of 2GB is much less worrying thas 75% of 256GB)?

**Comment by tacaswell** [comment]
Do we know what callbacks or monitors they had running during this?

**Comment by danielballan** [comment]
No, I posted all the information I have. I think it's likely this is a local configuration issue, but there's no harm in doing some basic checks.

**Comment by RuipengLi** [comment]
It ran with 32G memory on xf11bm-ws1.

**Comment by danielballan** [comment]
Here's one example of a place in the callbacks where we cache N items for an N-point scan. I don't think this itself explains 75% usage of 32G, but we might follow the pattern elsewhere. I'll try to avoid this as I write our "next generation" callbacks.

https://github.com/NSLS-II/bluesky/blob/7eea5f30d5e3a4c386585e23d17048b16cdac776/bluesky/callbacks/core.py#L343

**Comment by mrakitin** [comment]
Should be resolved via https://github.com/bluesky/bluesky/pull/1513.
