### ISSUE TITLE
A general pattern for handling dark frames

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky#1150]
This is a place to synthesize several disparate discussions on the handling of dark frames in bluesky. This may or may result in adding actual code to bluesky itself. I hope it will lead to converging on a "best practice" that we can document.

## Streams vs Runs

In [this portion of xpdacq](https://github.com/xpdAcq/xpdAcq/blob/b676faacaec3636a64d2b6e5208cfa77c1b99672/xpdacq/xpdacq.py#L103-L164) coauthored by @chiahaoliu and myself with subsequent development by @CJ-Wright, a plan preprocessor, `periodic_dark` interposes itself in the plan logic to create special Runs with a dark frame. Subsequent Runs have that "dark run" `uid` in their metadata, and downstream analysis code can use this to cross-reference and perform subtraction.

@mrakitin has recently [prototyped a different approach for QAS](https://github.com/NSLS-II-QAS/profile_collection/pull/2/commits/149813fbf92fb1601fa5c40753966c696905e055), which creates a special Event Stream (`'dark'`) in every run that will contain at least one Event with a dark image. The same actual exposure and the file that it's stored in may be used across several Runs.

Advantages of the 'Dark Stream' approach:
* The data in a run is self-contained. Exporters don't need to encode special knowledge (i.e. checking that "dark run" `uid`) in order to include complete information. Any given run directly references all the data it needs to be interpreted.
* It allows for the possibility of taking multiple dark frames during a run. This flexibility may not be needed in all cases, but it doesn't cost anything to have it.

## Use of RE.proprocessors

In the original xpdacq implementation, the `periodic_park` preprocessor is applied to all plans by subclassing the `RunEngine`. At the time, this was the simplest way of applying a preprocessor to all plans. But now, it could simply be appended to `RE.preprocessors`.

## Separation of Book-keeping and Automated Dark Frame Capture

The implementation of `periodic_dark` tightly couples the book-keeping (cross-referencing dark frames) to the code that decides when to take a fresh dark frame. It would be better to cleanly separate these things, so that the book-keeping logic can be reused even when dark frames are only acquired manually, or when a different type of dark-frame-taking logic is incorporated.

cc @DanOlds

**Comment by mrakitin** [comment]
A demo is alive via a binder, see https://github.com/NSLS-II/dark-subtraction-demo.

**Comment by danielballan** [comment]
See https://github.com/bluesky/bluesky-darkframes.
