### ISSUE TITLE
Loosen per_step requirements

### ISSUE THREAD

**Issue by CJ-Wright** [bluesky/bluesky#1168]
It might be nice to loosen the `per_step` signature requirements. For instance one could make a per_step which has some kwargs and use partial to set them (or just leave them defaulted). This would enable more flexable `per_step` logic, rather than making many per_steps which perform mostly the same logic, but with minor differences.

**Comment by danielballan** [comment]
Seems related to discussion raised in #1149 but it's not clear from this post which arguments you want to `partial` out. Can you give 2-3 examples?

**Comment by danielballan** [comment]
Now I think I better understand the request here. Addressed by #1302.
