### ISSUE TITLE
Kafka callback

### ISSUE THREAD

**Issue by CJ-Wright** [bluesky/bluesky#1177]
It would be nice to have a kafka version of the ``bluesky.callbacks.zmq`` system.

## Expected Behavior
Our current ZMQ things but kafka (with guaranteed delivery) 

## Current Behavior
We only have ZMQ, which can drop documents on the floor.

**Comment by jklynch** [comment]
PR #1209 addresses this issue.

**Comment by danielballan** [comment]
As noted in #1209 this work is being done in a separate repo so it is not bound to the bluesky release cycle. See https://github.com/bluesky/bluesky-kafka.
