### ISSUE TITLE
new plots placed under the task bar by default

### ISSUE THREAD

**Issue by prjemian** [bluesky/bluesky#1180]
Running ipython on linux from X11 server on Windows using Mobaxterm (an app that packages CygWin for Windows).  And that Windows is run from a Citrix server.  In the Windows session, the task bar is placed on the left of the screen (not at the bottom as is default).

Using the BestEffortCallback, new plots *always* appear underneath the Windows task bar, as if they have not considered that possibility.  Here's a screen shot:
![Clipboard01](https://user-images.githubusercontent.com/2279984/57655207-b34c1800-759b-11e9-9a95-cc7aa0a94f3e.jpg)

## Expected Behavior
Geometry of any task bar(s) should be considered when placing a new plot window on screen.

## Current Behavior
Plots are blocked by the task bar and need to be moved by the user.

## Possible Solution
Ask the window manager for the available rectangle boundaries in which a new window will not be blocked.

## Steps to Reproduce (for bugs)
See first paragraph.  Might be able to reproduce using linux remote terminal but be sure to move the task bar to the left of the screen.

## Context
Only annoying since the text on the left of the plot is occluded.  The window must always be moved to reveal full content.

## Your Environment
As stated above.

**Comment by tacaswell** [comment]
Does this happen if you just use `plt.plot()` from an IPython terminal?  

I am not sure of the top of my head what the Qt new window placement rules are...

**Comment by prjemian** [comment]
I'll use [this code](https://matplotlib.org/users/pyplot_tutorial.html#pyplot-tutorial) to test and show a screen shot.

**Comment by prjemian** [comment]
Simpler system.
host computer: Windows 10
VirtualBox guest: linuxmint
task bar placement: left side
window placement: on screen, does not block task bar
![Clipboard04](https://user-images.githubusercontent.com/2279984/57711541-85ff7880-7634-11e9-830a-247bc3319b25.jpg)

-----

next comes the system as reported initially

**Comment by prjemian** [comment]
Initial system: Windows 10
Citrix server and window manager: Windows Server 2016 Standard, task bar on left
X11 Server: MobaXterm
linux workstation: RHEL7
window placement: on screen, does not block task bar
![Clipboard01](https://user-images.githubusercontent.com/2279984/57712276-e0e59f80-7635-11e9-9d6d-c64f0c140a24.jpg)

**Comment by prjemian** [comment]
FWIW, the ipython session reports these version in use:

```
In [2]: !conda list qt
# packages in environment at /share1/bluesky/conda_envs/bluesky:
#
# Name                    Version                   Build  Channel
pyqt                      5.6.0            py37h8210e8a_8    conda-forge
pyqtgraph                 0.10.0                     py_5    conda-forge
qt                        5.6.3                h8bf5577_3
qtconsole                 4.4.3                    py37_0
qtpy                      1.5.2              pyh8a2030e_0    conda-forge

In [3]: !conda list matplotlib
# packages in environment at /share1/bluesky/conda_envs/bluesky:
#
# Name                    Version                   Build  Channel
matplotlib                3.0.3                    py37_0    lightsource2-tag
matplotlib-base           3.0.3                    py37_0    lightsource2-tag
```

**Comment by stan-dot** [comment]
@prjemian does this happen with the latest version still? https://github.com/bluesky/bluesky/issues/1180#issuecomment-492296256

**Comment by prjemian** [comment]
I'll test again next week.

**Comment by prjemian** [comment]
Initial system: Windows 11
Citrix server and window manager: Windows Desktop 2022, task bar on left
X11 Server: MobaXterm
linux workstation: RHEL9
window placement: on screen, does not block task bar

![image](https://github.com/user-attachments/assets/1ac09fc8-36a8-4d32-9ca5-510f50388e6c)

**Comment by prjemian** [comment]
In short, problem has been solved (and various components have been upgraded) since my initial report.
