### ISSUE TITLE
add requirements-dev.txt

### ISSUE THREAD

**Issue by jklynch** [bluesky/bluesky#1202]
I have to install several dependencies to run bluesky tests:
  pytest
  cloudpickle
  jupyter
  ophyd
  matplotlib
  pandas
  zmq
Some of these are listed in event-model requirements-dev.txt, but not all.

## Possible Solution
A requirements-dev.txt file with those dependencies would make setup easier.

**Comment by danielballan** [comment]
We have `dev-requirements.txt`, which is inconsistent with our other repos and also does not sort alphabetically next to `requirements.txt` so is harder to discover. I've been weighing whether we should rename it, and this seems like good evidence that we should.
