### ISSUE TITLE
Fix bluesky-0MQ-proxy CLI on Windows.

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky#1220]
## Expected Behavior
```
bluesky-0MQ-proxy ...
```
should run.

## Current Behavior
Windows report that it is not found.

## Possible Solution
Change `setup.py` to use `entry_points` instead of `scripts`. That is, apply [this approach we use in caproto](https://github.com/caproto/caproto/blob/5cef5778a2db0544bf3d989774ca14af78775196/setup.py#L62-L71) to [bluesky on this line](https://github.com/bluesky/bluesky/blob/d26253e1a096018bf0e2d5885a655344e24a48bc/setup.py#L17).

**Comment by jklynch** [comment]
Should scripts/bluesky-0MQ-proxy move into bluesky.callbacks.zmq.py as a main method so we can say

`'bluesky-0MQ-proxy = bluesky.callbacks.zmq:main'`

in setup.py? Or bluesky.commandline.zmq_proxy.py?

Or did you have something else in mind?

**Comment by danielballan** [comment]
Current approach in the PR is better than what I had in mind.

**Comment by jklynch** [comment]
resolved by PR #1221
