### ISSUE TITLE
Matplotlib figure: broken "Edit axis, curves and image paramaters"

### ISSUE THREAD

**Issue by bisogni** [bluesky/bluesky#1241]
Matplotlib figure doesn't allow anymore to select the "y" axis for teh "Edit axis, curves and image paramaters" but only provide the first axis after the upgrade. This function was very useful and working before. Hope it can be fixed.

**Comment by danielballan** [comment]
Hm, I'm not sure what to make of this change. Is this a matplotlib change, @tacaswell?

**Comment by tacaswell** [comment]
visited SIX, this issues is local to one of their workstations.
