### ISSUE TITLE
add SuspendWhenChanged from apstools

### ISSUE THREAD

**Issue by prjemian** [bluesky/bluesky#1250]
Add [`SuspendWhenChanged()`](https://github.com/BCDA-APS/apstools/blob/c10183a40d6cbd88e3919b2447bf9eb8537610f0/apstools/suspenders.py#L25) from [apstools](https://apstools.readthedocs.io/en/latest/source/_suspenders.html?highlight=SuspendWhenChanged#module-apstools.suspenders)

## Expected Behavior
Suspend when the monitored value deviates from the expected. Only resume if allowed AND when monitored equals expected. Default expected value is current value when object is created.

## Current Behavior
A new suspender for general use.

## Possible Solution
See apstools, as above.

## Steps to Reproduce (for bugs)
n/a

## Context
Using it at APS.

## Your Environment
linux-x86_64, python 3.6 and 3.7

**Comment by mrakitin** [comment]
Isn't it covered by https://github.com/bluesky/bluesky/pull/1247?

**Comment by prjemian** [comment]
closing as duplicate

**Comment by mrakitin** [comment]
Actually, I didn't mean this issue to be closed, as #1247 is its implementation via a PR. It can be reopened and linked in #1247 by one of the [GitHub keywords](https://help.github.com/en/articles/closing-issues-using-keywords). Up to you, @prjemian.

**Comment by prjemian** [comment]
OK, re-open and edit #1247 so it closes this when merged.

**Comment by mrakitin** [comment]
Thanks. Sorry about the mess.

**Comment by danielballan** [comment]
Heh, I _thought_ I had seen this before.
