### ISSUE TITLE
always construct live plots in the same thread as the RunEngine event loop

### ISSUE THREAD

**Issue by jklynch** [bluesky/bluesky#1268]
At BMM during testing with bluesky 1.6.0rc2 an issue was seen with LivePlots that looks like this:
```
QObject::startTimer: Timers can only be used with threads started with QThread
```

## Possible Solution
Construct all plots in the RunEngine event loop.

## Steps to Reproduce (for bugs)

1. install 2019C3.1.1rc3 environment:
```
xf06bm@xf06bm-ws1 [~] > CONDARC= conda create -p /tmp/new-stuff collection=2019C3.1.1rc3 -c https://repo.anaconda.com/pkgs/main -c https://conda.anaconda.org/nsls2forge --no-channel-priority --override-channels
```
2. Run bsui
3. RE(linescan(xafs_y,'i0', -2, 2, 5, force=True))

**Comment by danielballan** [comment]
Closed by #1285
