### ISSUE TITLE
LivePlot window problem when legend too large

### ISSUE THREAD

**Issue by prjemian** [bluesky/bluesky#1270]
In https://github.com/APS-USAXS/ipython-usaxs/issues/309, @jilavsky reports

> When graphs are opened for too many scans, matPlotLib used to generate these has bug. Graphs become useless and there does not seem obvious way to fix this.

See the attached picture in that issue.

## Expected Behavior
For unattended, continuous operation over long periods of time (such as a weekend), the plot windows must be stable.

## Current Behavior
When the legend grows too large (@jilavsky, can you provide some numbers here?), problems happen (@jilavsky, can you be more specific?)

## Possible Solution
1. Add an option to set the maximum number of traces shown in a single window. 
1. Add an option to open new window after *n* number of traces.
1. other

**Comment by jilavsky** [comment]
After today testing, this seems to start impacting the shape of graphs when legend is around 18-20 lines. There is no hard limit as it depends on physical size of image vs size of legend. Two solutions come to my mind: 1.  limit display to last 10-15 scans, or (which is more elegant solution I implemented in Irena): 2. decimate legend to display at most N (N~10-15) items while keeping all traces in the graph. In this case code is needed, which when needed limits legend to show every second (third, etc...) item in the legend.

**Comment by danielballan** [comment]
Thanks @jilavsky. I believe that adding the option to show only the most recent N traces has been previous proposed and well received. I think we can go with that and see if it works well.

**Comment by prjemian** [comment]
We have a solution, added to the [apstools]() package today.  It needs one more change but will be ready to pull into bluesky at that point.  Please stand by...

This code:

```
        # pick out only the traces that contain plot data
        # skipping the lines that show peak centers
        lines = [
            tr
            for tr in lp.ax.lines
            if len(tr._x) != 2 or len(tr._y) != 2 or tr._x[0] != tr._x[1]
        ]
```

needs to consider the possibility that the trace only has one data point.  Since the lines that plot peak centers have exactly two points with identical X values, it is easy to find them but we need to trap the case where we only have 1 point.  Like this:

```
        # pick out only the traces that contain plot data
        # skipping the lines that show peak centers
        lines = [
            tr
            for tr in lp.ax.lines
            if len(tr._x) != 2 or len(tr._y) != 2 or (len(tr._x) == 2 and tr._x[0] != tr._x[1])
        ]
```

**Comment by prjemian** [comment]
Done in https://github.com/BCDA-APS/apstools/commit/f4ed8a3125c91d1946fb8c2233b8f7111c3be374

I'll make a PR on this tomorrow.

**Comment by danielballan** [comment]
See also https://github.com/bluesky/bluesky-mpl/issues/4 where this "show last N traces" was first proposed.
