### ISSUE TITLE
exception traces are reported too deeply, in most cases

### ISSUE THREAD

**Issue by prjemian** [bluesky/bluesky#1274]
As noted in https://github.com/aps-8id-trr/ipython-8idiuser/issues/46, 

> The exception traces are too deep, in most cases. 

## Expected Behavior
> We expect such exceptions should be caught by the RunEngine, then raised as a new `PlanException` with the focus on the user plan step that provoked the exception. A terse mention in the `PlanException` would mention the specific deeper exception without the verbose trace. To preserve valuable diagnostics, the RunEngine could log separately the deeper exception reports.

Or, have a programmatic option to show them on console.

## Current Behavior
> When a problem is due to a user's plan, the exception is raised from a deep level in the bluesky framework and passed directly to the console. 

## Possible Solution
> This is an opportunity to improve the exception handling in the RunEngine. 

## Steps to Reproduce (for bugs)
For example, see https://github.com/aps-8id-trr/ipython-8idiuser/issues/114

## Context
Users have a difficult time reading through the exception traces.  Most of the report is from code in the bluesky framework with which the user does not interact.  The actual problem is buried in the weeds of detail.

**Comment by prjemian** [comment]
Seems that the proposed `PlanException` would be raised from the Msg handler.

**Comment by prjemian** [comment]
Labeled as bug but that's an opinion.  Alternatively could be an enhancement.  I picked bug since that is the way it works in the code now.

**Comment by prjemian** [comment]
Possible duplicate of #1244 with addition of logging the intercepted lower-level exception.

**Comment by stan-dot** [comment]
@prjemian can we add a 'good first issue' tag to this?

**Comment by prjemian** [comment]
duplicate (in principle) of: #1244 (now closed) and #1138 (now open)

I yield to #1138
