### ISSUE TITLE
additional requirement for release 1.4.1

### ISSUE THREAD

**Issue by prjemian** [bluesky/bluesky#1283]
Just encountered this exception using bluesky 1.4.1:

```
AttributeError: 'Legend' object has no attribute 'draggable'

In [4]: matplotlib.__version__                                                                                        
Out[4]: '3.1.1'

In [5]: bluesky.__version__                                                                                           
Out[5]: '1.4.1'
```

Referenced here: https://github.com/bluesky/bluesky/pull/1149#issuecomment-467969441

In MatPlotLib's [*API Changes for 3.1.0*](https://matplotlib.org/3.1.0/api/api_changes.html#removals)

> legend.Legend.draggable (use legend.Legend.set_draggable() instead)

So, for bluesky 1.4.1, need matplotlib < 3.1.0 as an additional requirement.

    conda install "matplotlib<3.1.0"

**Comment by tacaswell** [comment]
This should be fixed in the 1.5 series and up?

**Comment by prjemian** [comment]
I believe so.  The fix is in master.  This is just a new note for 1.4.1.  Could add as note to the [release page](https://github.com/bluesky/bluesky/releases/tag/v1.4.1)?

**Comment by tacaswell** [comment]
I don't know of any projects that go back and note what future versions of their dependencies go back and note where old versions of their project stop working, but I think adding a note to the release page is a good place to put that.

**Comment by tacaswell** [comment]
There are projects that aggressively pin the version of their dependencies back, but I am not convinced that the utility of that out weighs the thrashing (need to release a new version of your code with new dependencies every time a dependency releases!) or the risk of it-would-work-but-is-unsolvable environments due to pessimistic pins.

**Comment by prjemian** [comment]
I agree we should not change any release packages.  But software moves on.  We could not anticipate this restriction but it is possible to note this on the release page.  Most innocuous action we could take.
