### ISSUE TITLE
Refactor built-in plans to use contingency_wrapper

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky#1288]
The `contingency_wrapper` is better than the `finalize_wrapper` because the "final plan" takes in the exception that was raised as the argument, which allows the clean up to target specific failure modes if desired.

Even where that capability isn't used, it would be an improvement I think to model using `contingency_wrapper` in our code so that users can easily discover it and find examples of its use.

**Comment by callumforrester** [comment]
Reviewers: @danielballan @tacaswell

**Comment by stan-dot** [comment]
should mark `finalize_plan` as deprecated?

`docs/tutorial.rst` tells the user to use `finalize_wrapper`, should that be changed?

@danielballan

**Comment by stan-dot** [comment]
files that mention `finalize_wrapper`
- `preprocessors.py`
- `/tests/test_generators.py` - testing specifically the function itself
- `/tests/test_new_examples.py` - also in `test_finalize`
- `/tests/test_run_engine.py` - the most clear location where it might be replaced


When I'm looking atthe `plan_patterns.py` I do not see any wrappers.
OTOH, `plan_stubs.py` contains references to wrappers, and those used there are: rewindable, contingency and relative_set.

I am not sure where the change is to be made.

**Comment by tacaswell** [comment]
I'm weakly against deprecating it.  In cases where you only want to do cleanup the simpler signature is nice.

I'm also sure we have some usage on the floor at facilities who have already deployed bluesky and the disruption of deprecating this does not seem worth the marginal gain of getting rid of name in the namespace.

On the other hand "pause for debug" was a bad idea (I think I wrote it).

Maybe we should only purge it from the narrative docs?

**Comment by prjemian** [comment]
Not seeing any current use of [`finalize_wrapper`](https://github.com/search?q=org%3ABCDA-APS%20finalize_wrapper&type=code), [`finalize_plan`](https://github.com/search?q=org%3ABCDA-APS+finalize_plan&type=code), or [`contingency_wrapper `](https://github.com/search?q=org%3ABCDA-APS+contingency_wrapper&type=code) in our standard kit.  An APS beam line _might_ be using any of these, but not likely.

**Comment by stan-dot** [comment]
should the issue be closed as not needed then? 
@danielballan  @prjemian

**Comment by prjemian** [comment]
The action for this issue might be to ensure the documentation for the various affected code contains the recommendation in the initial statement here:

> The contingency_wrapper is better than the finalize_wrapper ...

**Comment by prjemian** [comment]
@stan-dot -- Thanks for picking this one up!

**Comment by stan-dot** [comment]
no worries!

**Comment by stan-dot** [comment]
![image](https://github.com/bluesky/bluesky/assets/56644812/183ecaff-7764-4dc3-a61d-a4a5f8288913)
so far only the `tutorial.rst` got modified with the menion, I'm happy to merge as is unless more places need the change
