### ISSUE TITLE
ENH: A new experiment command

### ISSUE THREAD

**Issue by ke-zhang-rd** [bluesky/bluesky#1358]
This feature get involved with bsui script and bluesky. To make discuss easier, I init discussion here. 
## Expected Behavior

**What will happen after execuate `bsui`**
1. 
```
Welcome to XXX beamline. May I have your name:
>>> 
```
```
If you know your gup number, type in below:
>>>
```
```
If you know your saf number, type in below:
>>>
```
2. Create session.json and store above data, if session.json exist, overwrite it.
3. init conda and ipython(current bsui)

**Inside bsui(ipython)**
- `bs.new_experiment` could overwrite session.json
- `bs.list_experiment_info` will show info
- `bs.end_experiment` will delete session.json
- `RE()` will check if session.json exist. If it's, load it as equivalent `RE.md['saf'] = "123456"` 

**Options**
`bsui  --develop` will skip prompt to make development easier
`bsui --continue `won't overwrite existing session.json
## Possible Solution

1. Three functions in bluesky. BMM has a [example](https://github.com/NSLS-II-BMM/profile_collection/blob/2b3c6918e5aac8e6ad05abc8cf63d77fc270a115/startup/08-user.py#L198) in 08-user.py

- `bs.new_experiment`
- `bs.list_experiment_info`
- `bs.end_experiment`

2. Update [bsui](https://github.com/NSLS-II/playbooks/blob/master/roles/bsui/files/bsui).A UI example:

3. A location and format of file `session.json`, maybe:
```
{
    'name': "Abc",
    'date': "yyyy-mm-dd HH:mm:ss.SSS",
    'gup': "123456",
    'saf': "123456"
}
```

**Comment by ke-zhang-rd** [comment]
@stuartcampbell 
@danielballan

**Comment by danielballan** [comment]
Can we move this to https://github.com/NSLS-II/nslsii? I don't think we want to develop this here. No changes to bluesky itself needed.

**Comment by ke-zhang-rd** [comment]
In my mind `new_experiment` could be a bluesky function.

**Comment by ke-zhang-rd** [comment]
This issue has been moved to https://github.com/NSLS-II/nslsii/issues/85
