### ISSUE TITLE
DatagramProtocol event loop not active during RunEngine execution

### ISSUE THREAD

**Issue by stashlukj** [bluesky/bluesky#1364]
The RunEngine doesn't allow the passed event loop to run while it executes the plans.

## Expected Behavior
The event loop should continue processing messages from the UDP port while the RunEngine executes its plans.

## Current Behavior
The event loop stops processing received datagrams.

## Possible Solution
I'm not sure if I am attacking this problem correctly with regard to the ophyd device implementation.

Example attached: https://gist.github.com/stashlukj/b1c014e90f23047d7bda73182a0355cd

Environment: Ubuntu 20.04, Python 3.8

**Comment by danielballan** [comment]
That situation may be a novel one for bluesky applications. I can see how, "Take whatever sensors I can find and run with that," makes sense in this context; it's just different that the one that bluesky originated in, which is more like, "I expect this set of senors and if one of them isn't connecting, bail."

I think the approach you have described makes sense in that context.
