### ISSUE TITLE
Device cannot be used as Flyer

### ISSUE THREAD

**Issue by ZLLentz** [bluesky/bluesky#1366]
## Expected Behavior

Device that implements `read_configuration` should be able to be used in a fly scan in `bluesky=1.6.2`

## Current Behavior

My `ophyd` `Device` that inherits `Device.read_configuration` blows up in the `collect` step here:
https://github.com/bluesky/bluesky/blob/3e298fde0abfba8ad99aea535ff4ee37c79d755a/bluesky/bundlers.py#L581-L588

Where on the last line the code tries to access what is in my case `4['value']`. 

`read_configuration` is meant to be something like
```
OrderedDict(('channel1',
             {'value': 5, 'timestamp': 1472493713.271991}),
             ('channel2',
             {'value': 16, 'timestamp': 1472493713.539238}))
```

So when we unpack the dictionary twice in this code block we are left with `config_key` as `'value'` and `config` as `5`. I assume these are meant to be `config_key` == `channel1` and `config` == `{'value': 5, 'timestamp': 1472493713.271991}`.

## Possible Solution

Not sure, I'm having trouble identifying what the contents of `collect_obj_config` are supposed to be.

## Steps to Reproduce (for bugs)

1. Run a fly scan with a device that implements `read_configuration`

## Context

Old scans no longer work

## Your Environment

`bluesky=1.6.2`
`ophyd=1.5.0`

**Comment by tacaswell** [comment]
This is fallout from #1337 / https://github.com/bluesky/bluesky/pull/1338 / https://github.com/bluesky/bluesky/pull/1351 .  


attn @jklynch

**Comment by jklynch** [comment]
Arg!

**Comment by jklynch** [comment]
Addressing this issue in #1369.
