### ISSUE TITLE
field shape of null

### ISSUE THREAD

**Issue by untzag** [bluesky/bluesky#1374]
big fan---first time opening an issue :wave: 

Bluesky Documentation [1] claims that None is a valid argument for field shape, but your schema does not accept None [2]. This is easy to fix, but I need direction: is this a bug in docs or a bug in the schema?

[1] http://nsls-ii.github.io/bluesky/hardware.html#ReadableDevice.describe
[2] https://github.com/bluesky/event-model/blob/f33e54ac88ca7fa8588acd41a1f7e41b7610c269/event_model/schemas/event_descriptor.json#L23-L28

**Comment by danielballan** [comment]
Hi @untzag! Thanks for catching this.

I seem to remember that in the very earliest days of the bluesky prototype (maybe predating schema validation?) we accepted None, and if you had asked me up to now I would have said that we still do—hence the erroneous docs.

Looking forward, seems to me we should correct the docs and let the schema remain strict about this. It saves all document consumers from needing to perform a None check before going on to deal with the shape as a tuple or list.
