### ISSUE TITLE
check of isinstance(obj, Movable) only accepts class attributes, rejecting potentially valid objects

### ISSUE THREAD

**Issue by untzag** [bluesky/bluesky#1377]
I'm trying to get yaqc-bluesky settable objects to work in a `grid_scan`, but bluesky is claiming that my arguments are invalid. In particular, my objects are failing to pass `isinstance(obj, Movable)` [1].

The `Movable` class is an abstract base class [2] which, according to the comment, should turn the `isinstance` check into, essentially, a check against the list of expected attributes. Not actually understanding the ABC magic, all I can say is that I can pass `hasattr` without passing `isinstance`:

```python
import bluesky
from bluesky.utils import Movable


EXPECTED_ATTRS = (
    'name',
    'parent',
    'read',
    'describe',
    'read_configuration',
    'describe_configuration',
    'set',
    'stop',
)


class Device(object):

    def __init__(self):
        for attr in EXPECTED_ATTRS:
            setattr(self, attr, None)


device = Device()
print("hasattr", all(hasattr(device, attr) for attr in EXPECTED_ATTRS))  # True
print("isinstance", isinstance(device, Movable))  # False
print("subclasshook", Movable.__subclasshook__(device))  # True
```

Even more strangely, when I play with your example notebook [3] your own ophyd motor objects also fail this `isinstance` check and, indeed, are rejected within `grid_scan` (Hello Bluesky.ipynb). Is it possible that this plan is just broken?

Any guidance would be appreciated---thanks! :smile: 

[1] https://github.com/bluesky/bluesky/blob/master/bluesky/plan_patterns.py#L431
[2] https://github.com/bluesky/bluesky/blob/master/bluesky/utils.py#L1519-L1548
[3] https://try.nsls2.bnl.gov/

**Comment by danielballan** [comment]
Good puzzle! It took me a minute to spot what is happening, but I think bluesky is correct here. We expect the _class_ to have those methods; that is, `__subclasshook__` is acting on `Device`, not `device`. Thus, any attributes added in `__init__` are added too late.

**Comment by untzag** [comment]
@danielballan thanks for your response

Is there a good reason to require them to be class attributes?

**Comment by untzag** [comment]
I've opened #1378 which changes this behavior to allow objects like above to pass. In my opinion bluesky should not be opinionated about how the class is constructed. Seems like what should matter is what exists after instantiation.
