### ISSUE TITLE
PersistentDict doesn't support __setitem__ on nested dictionaries

### ISSUE THREAD

**Issue by MikeHart85** [bluesky/bluesky#1388]
Reported by @ambarb during CSX deployment.

## Expected Behavior
```
RE.md['sample'] = {}
RE.md['sample']['foo'] = 'bar'
RE.md
<PersistentDict {'sample': {'foo': 'bar'}}>
```

## Current Behavior

Fails quietly, without error messages:

```
RE.md['sample'] = {}
RE.md['sample']['foo'] = 'bar'
RE.md
<PersistentDict {'sample': {}}>
```

## Possible Solution

Needs further investigation. Something appears to go wrong in the base class `__setitem__` implementation.

## Steps to Reproduce (for bugs)

See above. Reproducible with any instance of PersistentDict, RE.md not needed.

## Context

Just trying to set up the dictionary and change values after initial setup.

## Your Environment

CSX, but should be reproducible with any instance of PersistentDict.

**Comment by MikeHart85** [comment]
Tagging for info @mrakitin

**Comment by danielballan** [comment]
Fix on the way....
