### ISSUE TITLE
LiveGrid needs to accept a title kwarg

### ISSUE THREAD

**Issue by mrakitin** [bluesky/bluesky#1396]
## Expected Behavior

We should be able to provide a title of a plot generated by LiveGrid`.

## Current Behavior

Not currently possible without a bulky workaround.

## Context

Requested by @andrewmkiss at SRX.

## Your Environment

`xf05id1-ws2` at NSLS-II SRX. See https://github.com/NSLS-II-SRX/profile_collection/pull/11 for details.

**Comment by tacaswell** [comment]
I think so.

**Comment by callumforrester** [comment]
Reviewers: @mrakitin @callumforrester

**Comment by callumforrester** [comment]
For scanspec I treated the title as an override
