### ISSUE TITLE
Best-effort callback - custom LiveTable

### ISSUE THREAD

**Issue by klauer** [bluesky/bluesky#1436]
Would it be reasonable to have a hook in the best effort callbacks to allow for customization of the classes used - such as a custom `LiveTable` subclass/implementation? If the answer is "yes", a similar hook for `PeakStats`, `LivePlotPlusPeaks`, etc. may follow.

Relevant source: https://github.com/bluesky/bluesky/blob/0a91b8b8a52509198ed5b884c208d58601424828/bluesky/callbacks/best_effort.py#L362

I admittedly don't know how this might fit into the overall future plans for BEC, which appear to be outlined here:
https://github.com/bluesky/bluesky/issues/1271

**Comment by danielballan** [comment]
Bottom line: I'd merge a PR adding hooks if you need them, but I'd be interesting to know how close bluesky-widgets is to meeting your use case(s). It is much more amenable to this kind of customization.

Best-effort callback is on the cusp of deprecation, so I'm inclined to avoid adding to its maintenance complexity if we can avoid it. I have add a comment to the issue you linked: https://github.com/bluesky/bluesky/issues/1271#issuecomment-779373922

**Comment by ambarb** [comment]
Would like to learn more about Bec on cusp of  deprecation. Open discussions with @prjemian @mrakitin @gfabbris and others it seems that bec fo hklpy presents some complications given how bec, live plot and live table are all inter-related.

Is there a document describing `bec.peaks` replacement or a fork we can have a look at?
