### ISSUE TITLE
ABCs for Devices that implement the "Bluesky Interface"

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky#1445]
@untzag and @ksunden have suggested adding some ABCs for the expected Bluesky Interfaces. ABCs would be a useful tool for scaffolding implementations of the Readble, Movable, and Flyable interfaces. I would want to avoid accidentally giving the impression that implementation _must_ subclass from them. A key selling point for Bluesky is that other libraries can implement its interfaces and be interoperable without a software dependency. In our documentation, we should emphasize that they are optional, to be used or referred to if they help, or ignored otherwise.

We should also be sure that these ABCs implement https://docs.python.org/3/library/abc.html#abc.ABCMeta.__subclasshook__ so that they will behave correctly if `isinstance` is used.

**Comment by untzag** [comment]
Suggest ABC for `Status` as well

**Comment by ksunden** [comment]
https://www.python.org/dev/peps/pep-0544/

Protocols are a more recent variant on the theme of ABCs. (Particularly aimed towards typecheckers like mypy, so that you can statically check duck typed classes)

As I read the PEP, the runtime `__subclasshook__` would still need to be implemented in order to do runtime isinstance checks, as Protocols are explicitly targetted to static checks

**Comment by ksunden** [comment]
(Note that the decorator version only does attribute existence checks, not signature checks, which is pretty much exactly what the present is movable test does, just without the benefits of being able to do static analysis)

**Comment by danielballan** [comment]
When writing these it would be useful to refer to https://github.com/bluesky/ophyd/blob/7937cd46e92e9ec2f7eec321dd5b1b1b71115e20/ophyd/device.py#L396-L402

**Comment by ksunden** [comment]
One idea that occurs to me:

Making these ABC's their _own_ small package that can be depended on (more easily than if it were integrated into bluesky. i.e. something with minimal to no transitive dependencies [probably backports of typing extensions])

While the idea is that they are duck typed still, a separate package would allow things like ophyd or yaqc-bluesky (among many others) to bring in the ABC as a superclass that will error if it is not implemented. (while maintaining their ability to _not_ do so and still pass both static type checks and runtime checks if they simply implement without an explicit superclass relationship)

I would expect such an ABC package to be of use to happi/typhos as well, though am personally less familiar with the internals there.

**Comment by untzag** [comment]
`device-model`

**Comment by thomascobb** [comment]
This would be helpful when we're looking at extending ophyd's fly-scanning capabilities later this year. Let me or @callumforrester know if we can help with this.

**Comment by danielballan** [comment]
I like the idea of prototyping this in Bluesky and then factoring it out. We should put some thought into what else might go there. It sounds like both Ophyd and Bluesky may grow a dependency on it, so it should have low (zero?) dependencies itself.

**Comment by ksunden** [comment]
I believe the only dependency will be `typing-extensions` and even then that can be dropped once 3.7 support is dropped (as Protocol is defined in the standard lib of 3.8+)
