### ISSUE TITLE
test test_table_external is stochastically failing

### ISSUE THREAD

**Issue by untzag** [bluesky/bluesky#1459]
`test_callbacks/test_table_external` [1] seems to be failing randomly. I can't track down exactly why---the fixtures or whatever that are creating the environment for that test are opaque to me.

[1] https://github.com/bluesky/bluesky/blob/master/bluesky/tests/test_callbacks.py#L150-L152

**Comment by cjtitus** [comment]
I don't have the power to close this, but #1430 should actually solve this problem completely, so this issue is now fixed! We can run our tests in peace (and with the knowledge that failures are actual failures)!

**Comment by mrakitin** [comment]
Closed via #1430.
