### ISSUE TITLE
How can I simulate 0-speed hover for UAVs?

### ISSUE THREAD

**Issue by Shulu-Chen** [bluesky/bluesky#1463]
## Expected Behavior

Operate UAVs hover at a certain place, with 0 speed but some altitude, like:
0:00:00.00>ADDWPT KL204 W2 400 0

## Current Behavior

"The entered velocity will be interpreted as a Mach number when a number smaller than 1.0 is entered."

## Possible Solution

What to know how should I control the UAVs hover at a very low velocity since the default setting would recognize very low speed as a Mach number.

**Comment by mrakitin** [comment]
Is it EPICS-operated?

**Comment by ksunden** [comment]
It sounds like you are looking for https://blueskyuav.co.uk/, which is unrelated to this repository.

**Comment by ksunden** [comment]
Actually, a bit more looking led me to this, which is probably actually what you want: https://github.com/TUDelft-CNS-ATM/bluesky

**Comment by Shulu-Chen** [comment]
Thanks! Yeah, I am doing on the TUDelft's BlueSky. Sorry for my fault.
