### ISSUE TITLE
IPython 7.30.0 incompatibility - RuntimeError: There is no current event loop in thread 'MainThread'

### ISSUE THREAD

**Issue by klauer** [bluesky/bluesky#1493]
## Expected Behavior
bluesky should work out of the box in a new installation with the latest IPython 7.30.0.

## Current Behavior

Exception gets raised:
```python
----> 1 RE(bluesky.plans.count([ophyd.sim.det]))

~/mc/envs/tiled/lib/python3.8/site-packages/bluesky/run_engine.py in __call__(self, *args, **metadata_kw)
    847                   "hit Ctrl-C twice to pause.")
    848
--> 849         self._clear_call_cache()
    850         self._clear_run_cache()  # paranoia, in case of previous bad exit
    851

~/mc/envs/tiled/lib/python3.8/site-packages/bluesky/run_engine.py in inner(self, *args, **kwargs)
    175     def inner(self, *args, **kwargs):
    176         with self._state_lock:
--> 177             return func(self, *args, **kwargs)
    178
    179     return inner

~/mc/envs/tiled/lib/python3.8/site-packages/bluesky/run_engine.py in _clear_call_cache(self)
    643         self._task_fut = None
    644         self._status_tasks.clear()
--> 645         self._pardon_failures = asyncio.Event(**self._loop_for_kwargs)
    646         self._plan = None
    647         self._interrupted = False

~/mc/envs/tiled/lib/python3.8/asyncio/locks.py in __init__(self, loop)
    258         self._value = False
    259         if loop is None:
--> 260             self._loop = events.get_event_loop()
    261         else:
    262             self._loop = loop

~/mc/envs/tiled/lib/python3.8/asyncio/events.py in get_event_loop(self)
    637
    638         if self._local._loop is None:
--> 639             raise RuntimeError('There is no current event loop in thread %r.'
    640                                % threading.current_thread().name)
    641

RuntimeError: There is no current event loop in thread 'MainThread'.
```

## Possible Solution

Short-term solution attempts:
* First guess of `set_event_loop(new_event_loop())` didn't do it.
* Second solution: downgrade to IPython 7.28.0 or less in the short-term.

## Steps to Reproduce (for bugs)

1. Install new environment as listed below
2. Run the following and observe the exception

```python
import ophyd.sim
import bluesky.plans
RE = bluesky.RunEngine({})
RE(bluesky.plans.count([ophyd.sim.det]))
```

## Context
Trying to insert data into tiled/mongo with bluesky and failing from the start.

## Your Environment
New conda environment with the following versions:
* Python 3.8.12
* IPython 7.30.0
* bluesky 1.8.1
* ophyd 1.6.3

**Comment by ZLLentz** [comment]
Confirming that this problem does not exist in IPython 7.29.0, but does exist in IPython 7.30.0

**Comment by ZLLentz** [comment]
https://github.com/ipython/ipython/pull/13269 for more context

**Comment by klauer** [comment]
7.30.0 was yanked from PyPI and 7.30.1 was released to patch this:
https://github.com/ipython/ipython/compare/7.30.0...7.30.1
I think we can close this issue. 

Solution: If you somehow managed to install IPython 7.30.0, upgrade to 7.30.1.

**Comment by tacaswell** [comment]
Do we want to learn enough about constraints files to ban IPython 7.30.0?

**Comment by klauer** [comment]
As 7.30.0 is a yanked version, I believe it's unnecessary to worry about such constraints. Pip should skip over it since 7.30.1 exists, to my understanding.

**Comment by ZLLentz** [comment]
Instead, perhaps we can catch the exception from this PR and raise another with a nicer message for the user? (I'm having trouble verbalizing what that message would be, but it seems like it would help)

**Comment by tacaswell** [comment]
If they yanked 7.30.0, then I think we can just move on!

**Comment by mrakitin** [comment]
Conda-forge still has the 7.30.0 available with the `main` label:
![image](https://user-images.githubusercontent.com/13209176/144489138-870bf00e-7d60-407b-acf3-00a6b0b826c1.png)

We may need to exclude it from our .yml files, etc. manually.

**Comment by tacaswell** [comment]
if it was yanked on pypi, we should ask to have it yanked on CF as well.

**Comment by klauer** [comment]
https://github.com/conda-forge/ipython-feedstock/issues/152

Any advice for the feedstock maintainer? I've never gone through the process myself.

**Comment by mrakitin** [comment]
Cool! For future us: open an issue/PR in https://github.com/conda-forge/admin-requests.
