### ISSUE TITLE
The BestEffortCallback fails to give a table or plots for more than 2 motors. 

### ISSUE THREAD

**Issue by maffettone** [bluesky/bluesky#1508]
## Expected Behavior
If 3 or more motors are given, it is appropriate for a BEC to not try and make assumptions about what should be plotted; however, it should at least give a table of positions.

## Current Behavior
The BEC prints no LiveTable, produces no Figures, and doesn't tell the user why. 
This largely happens because of this return statement in the `descriptor` processing https://github.com/bluesky/bluesky/blob/05238c2177c0d4b5e58905d65395b079454aabfb/bluesky/callbacks/best_effort.py#L233-L236
occurring before the LiveTable is  set up. 
https://github.com/bluesky/bluesky/blob/05238c2177c0d4b5e58905d65395b079454aabfb/bluesky/callbacks/best_effort.py#L362-L369

## Possible Solution
- The quickest solution is to move the LiveTable setup above the Plot setup. 
- A  better solution would be to warn the user about this behavior and why its occuring. 
- A better solution would be to refactor the plot setup into a 'private' separate function, so that the return statement doesn't skip anything now or in the future. 
- A potentially better but contentious solution is to assume the first 2 motors are most important and plot them while warning the user that this is happening. 
- A chaotic solution is the plot two random motors. 

## Steps to Reproduce (for bugs)
```python
cat = databroker.catalog["csx_local"]
run1 = cat[151430]
run2 = cat[151431]
replay(run1.documents(fill="yes"), BestEffortCallback(), burst=True) # Works as expected, 2 motors
replay(run2.documents(fill="yes"), BestEffortCallback(), burst=True) # Does not work, 4 motors
```

## Context
Extending a plan to move a 2 pairs of correlated motors as a grid scan instead of a line scan. That is {top_x, bottom_x} and {top_z, bottom_z}. 
I presume the desired behavior could be accomplished using the `hints` field in the metadata; however, it'd be nice for a "Best Effort" solution that at least does something. 

## Your Environment
nsls2-collection-2022-1.0-py37

**Comment by maffettone** [comment]
I am happy to take the lead on this and issue a PR for any of the possible solutions described above, but would like to take some opinions before I do.

**Comment by tacaswell** [comment]
> A chaotic solution is the plot two random motors.

🤣 

> A better solution would be to refactor the plot setup into a 'private' separate function, so that the return statement doesn't skip anything now or in the future.

This is probably the best solution, if not too disruptive to write.

----

It may also be possible to work through 
https://github.com/bluesky/bluesky/blob/05238c2177c0d4b5e58905d65395b079454aabfb/bluesky/callbacks/best_effort.py#L115-L133 and sort out how to have the plan tell BEC which 2 (of the 4 motors @cmazzoli is scanning here) actually matter, however we should fix this bug no matter what.

**Comment by maffettone** [comment]
It shouldn't be too disruptive, but I'll rely on unit tests to tell me if I broke anything in the process O:). 

Yea, this is the work-around I suggested in the interim.

**Comment by cmazzoli** [comment]
Hi guys,
I am a little confused (starting from the language.. I am sorry).
Can we test the existing script left by Phil in our directory, or should we wait for some extra work to be done behind the scenes?
Please let me know. Thanks.
Have a nice weekend,
Claudio

**Comment by maffettone** [comment]
@cmazzoli Not a worry! 
The script I left in your directory should solve the problem for the interim. You should expect just 2 motors in the table and in the plots, while the other 2 are ignored by the callback. Definitely ping me on slack if that isn't working.

This github issue is for a long term solution, so that no one is ever surprised again when their table just disappears after adding more motors.

**Comment by cmazzoli** [comment]
Ok, thanks a lot. Understood.
Next week we will try (we have users now).
Have a nice weekend,
Claudio
