### ISSUE TITLE
Add abstractmethod decorators to all protocols

### ISSUE THREAD

**Issue by coretl** [bluesky/bluesky#1547]
## Expected Behavior
I like type checking protocols with mypy. For example, this gives an error with mypy to say that `Implicit` is not a `Readable` because it is missing the `read` method:
```python
from bluesky.protocols import Readable

class Implicit:
    def describe(self):
        return {}

r: Readable = Implicit()
```
However, when defining the class it would be good to declare what protocols it implements. You can do this by subclassing:
```python
from bluesky.protocols import Readable

class Explicit(Readable):
    def describe(self):
        return {}

r: Readable = Explicit()
```
Unfortunately this makes mypy happy with the assignment because we define stub methods in the protocols. The way to make mypy correctly error seems to be to add the `@abstractmethod` decorator to all the stub methods of the protocols:
```python
class Readable(Protocol):
    @abstractmethod
    def read(self) -> Dict[str, Any]:
        ...
```
As defined in the docs: https://mypy.readthedocs.io/en/stable/class_basics.html#abstract-base-classes-and-multiple-inheritance

> Note that mypy performs checking for unimplemented abstract methods even if you omit the [ABCMeta](https://docs.python.org/3/library/abc.html#abc.ABCMeta) metaclass. This can be useful if the metaclass would cause runtime metaclass conflicts.

Any objections if I decorate all protocol class methods with this?

**Comment by coretl** [comment]
@ksunden @untzag @tacaswell

**Comment by untzag** [comment]
In my humble opinion this seems reasonable. We use `@abstractmethod` in base classes in our stack and I really like the behavior---both static analysis and runtime.

I will admit to ignorance on how this works when you have `Protocol` in the inheritance tree. Protocols cannot be instantiated, and I'm not sure how that works for their children. Personally my plan is to not treat these protocols as base classes, as that opens the door to a mixing of interface definition and implementation that I don't personally want to do. The whole "protocols cannot be instantiated" thing is run time though, and you are thinking about static checks from what I can tell.

**Comment by coretl** [comment]
> Protocols cannot be instantiated, and I'm not sure how that works for their children

Immediate subclasses of `Protocol` cannot be instantiated, but their subclasses can. So we can't `Readable()` but we can `MyReadable()`.

> Personally my plan is to not treat these protocols as base classes, as that opens the door to a mixing of interface definition and implementation that I don't personally want to do.

That's interesting, how do you plan to check that your classes implement their protocols correctly? Do you have an ABC that implements Readable? For the first time in my life I feel like java does this better, I want to write `class MyReadable(ophyd.Device) implements Readable, Settable`, and the closest I seem to be able to get in python is `class MyReadable(ophyd.Device, Readable, Settable)`...

**Comment by ksunden** [comment]
https://peps.python.org/pep-0544/#merging-and-extending-protocols

More info on subclassing protocols . Specifically, if a class does not directly inherit from Protocol it is not considered a Protocol, and thus can be instantiated (though of course any abstract methods must be implemented to do so).

I have no issue with annotating protocol members.

That said, if we are anticipating explicit subclasses, I think it may be time to reconsider if the protocols should be their own package to avoid complicated dependency relationships for projects that only rely on the protocols.

**Comment by ksunden** [comment]
@coretl mypy will check implicit subclasses 

```python
dev: Readable = ImplicitDevice()
```

**Comment by ksunden** [comment]
The main advantage of protocols over traditional ABCs is that they _don't_ need to be subclassed to be identified as adhering to the protocol.

**Comment by untzag** [comment]
> how do you plan to check that your classes implement their protocols correctly

In my mind this the right way to check:

https://github.com/bluesky/yaqc-bluesky/blob/master/bluesky_protocols.py
https://github.com/bluesky/ophyd/blob/master/ophyd/tests/test_bluesky_protocols.py

**Comment by klauer** [comment]
I'm a fan of the explicit approach for the reasons you've listed, @coretl. The upsides to the approach strongly outweigh the seemingly minor downsides.

I would then agree that adding `@abstractmethod` decorators to all such protocol methods is appropriate.

> That said, if we are anticipating explicit subclasses, I think it may be time to reconsider if the protocols should be their own package to avoid complicated dependency relationships for projects that only rely on the protocols.

What would such a complicated dependency relationship look like, assuming all of the base protocols continue to exist in `bluesky.protocols`? Is there a specific scenario you're thinking of?

**Comment by coretl** [comment]
@evalott100
