### ISSUE TITLE
Memory creep in RunEngine

### ISSUE THREAD

**Issue by imohacsi** [bluesky/bluesky#1553]
There is a slow gradual increase in memory usage during large scans that can reach quite extreme levels when re-using the same RunEngine.  I believe this is the same issue that Klaus reported but was never examined in detail.

## Expected Behavior
Since the RunEngine has an emit-and-forget mentality, memory usage is expected to keep low and roughly constant.

## Current Behavior
There is a gradual increase in memory usage during the scan, it stays high afterwards and is cumulative after multiple subsequent scans. I.e. it can get out of hand upon prolonged usage. There was a suspicion of some internal caching within the RunEngine, but destroying or re-constructing the RE does not reset the memory usage.

## Steps to Reproduce (for bugs)
Run the following code:
```
from bluesky import RunEngine
from bluesky.plans import scan
from ophyd.sim import motor1, det1

RE = RunEngine()
res = RE(scan([det1], motor1, -3, 5, 50000)) 
```
The memory usage of my python process stands at 1.3 GB, which is much more than anticipated! If I run another scan the memory usage will nearly double and still remains reserved. The third time another GB...

## Possible Solution
Upon some snooping I found a way to reset the memory usage but it's linked to a really weird behavior. The guilty object is the `_status_tasks` queue of the RunEngine. However if I simply clear it, nothing happens:
```
RE._status_tasks.clear()
```
The memory usage stays the same despite de-referencing all queue elements. I have to explicitly call the garbage collector to clean up the memory: 
```
RE._status_tasks.clear()
import gc
gc.collect()
```
The garbage collector cleaned up `5700245` objects. Now the memory usage of the Python process is back to 200 MB.
**Note: ** The above test script is only using simulated hardware and trying to run the loop at maximum speed. It might be that with real hardware the tasks don't pile up like above.

## Your Environment
Anaconda Python 3.8.3 with IPython 7.16.1 on windows, also tested with Python 3.9 on RedHat 7.

**Comment by prjemian** [comment]
Are these reports related?

- https://github.com/APS-USAXS/usaxs-bluesky/issues/500
- https://github.com/APS-USAXS/usaxs-bluesky/issues/522

**Comment by untzag** [comment]
Are you using Bluesky 1.10.0? I believe this was fixed, we ran into the same thing.

https://github.com/bluesky/bluesky/pull/1513

**Comment by tacaswell** [comment]
Great, sorry the issue was there, but happy the fix was just "upgrade"!
