### ISSUE TITLE
Suggestion: Merge DatumPage and StreamDatum functionality into EventPage

### ISSUE THREAD

**Issue by coretl** [bluesky/bluesky#1560]
When trying to use StreamResource and StreamDatum it occured to me that EventPage was very nearly what I wanted, and maybe we could iterate on that rather than making something new. I suggest to following changes to EventPage:
- `seq_num` is either an array of N integers or a slice object (dict with `start` and `stop` keys)
- `data[key]` is either an array of data values or a single resource slice reference
- `filled[key]` is a single bool rather than an array of N bools
- `timestamps` is optional

After conversations with @danielballan we could also remove Datums from this world and make explicit references to slice information in the resource reference, so `data[key]` could be:
- In `Event`
  - If `filled`, the actual data, e.g. `2.5`
  - If not `filled`, a pointer to an index within a resource uid, e.g. `uid/5`
- In `EventPage`
  - If `filled`, the actual data array, e.g. `[2.5, 3.5, 4.5]`
  - If not `filled`, a pointer to a slice within a resource uid, e.g. `uid/5:8`

![EventPage suggestion](https://user-images.githubusercontent.com/101418278/210523426-69df9cbd-fcaf-4ca9-befb-786d96016c56.png)

This means that a 1 MHz point detector could produce a single EventPage every second with no million point JSON structures within it.

Note that unless a rewind has happened, the slice information in the resource reference will be the same as in `seq_num`, but after a rewind `seq_num` may repeat, so will be less than the slice information in the resource reference.

This would make #1558 a lot simpler

**Comment by coretl** [comment]
@danielballan @tacaswell this is now updated in light of yesterday's conversation so ready for further comments

**Comment by coretl** [comment]
@callumforrester @diamondjoseph this may be of interest

**Comment by tacaswell** [comment]
A major concern I have is that this would make the current "list of Events" <-> "EventPage" equivolence much harder to maintain as now we need to solve the problem of "I have a _bunch_ of datum" <-> "a slice of a resource".  

Starting clean with the more restricted assumptions of StreamDatam and StreamResource where to avoid having to solve this problem.
