### ISSUE TITLE
bug: Calling describe during stage

### ISSUE THREAD

**Issue by callumforrester** [bluesky/bluesky#1594]
## Expected Behavior
Certain devices, such as [FileStoreBase](https://github.com/bluesky/ophyd/blob/5c413cc0848ef035b9839de328064d6af47b589b/ophyd/areadetector/filestore_mixins.py#L94), lock themselves while staged and do not permit calls to `describe()`.
In 1.10, the RE did not appear to call `describe()` on any devices that were already staged thanks to caching in the run bundler, so this worked as expected.

## Current Behavior
In 1.11, the way the caching works seems to have changed and there are now some calls to `describe()` while a device is staged, which causes fatal exceptions. 
The issue stems from a call to `bpp.declare_stream`  (for example in `scan_nd`) ([line 1009](https://github.com/bluesky/bluesky/blob/e38b2dab394300fff1cc02fbc5bd2fba23cbfdc1/bluesky/plans.py#L1009)), which is wrapped in a stage decorator. This call sets off the device.describe method in ophyd after the device has already been staged.

## Possible Solution
I am unsure at this stage if it is better to somehow remove the lock from `FileStoreBase` or put the caching back. Do we know why the file store lock was made in the first place? 

## Steps to Reproduce (for bugs)

1. Create an OphydDetector with a file store based component, such as an HDF5 plugin. [Example here](https://github.com/DiamondLightSource/dodal/blob/main/src/dodal/devices/areadetector/adsim.py).
2. Run a plan such as `count` or `scan_nd` with this detector.
3. It will raise an exception with the error message `Modifying after lock`.

**Comment by tacaswell** [comment]
The issue is that we are calling describe (or read) which causes the list of keys that can be in the output to be locked before calling trigger (which actually generates said list).

**Comment by mrakitin** [comment]
We are seeing this issue at NSLS-II ISS.

**Comment by callumforrester** [comment]
From discussions on calls and in slack: Solution for now is to pull pre-declare (https://github.com/bluesky/bluesky/pull/1542) and fix in a later version. Will make a separate issue for that.

**Comment by mrakitin** [comment]
@callumforrester, I hit this issue another time. What temporary workaround did you use on your side?

**Comment by callumforrester** [comment]
@mrakitin downgrading to 1.10 :)

**Comment by tacaswell** [comment]
This is fixed in 1.12 to no longer pre-declare by default.

The core problem is still that the exact keys produced by some devices are not set until `trigger` 😱 .

**Comment by callumforrester** [comment]
Wonder if it would be nice if there was a way for devices to pre-declare _that they are unable to_ pre-declare?

Will close this regardless, cheers!

**Comment by tacaswell** [comment]
The late declaration was to support a feature that we no longer want to try and support.  We ripped all of the actual leveraging of it out but not the machinery to support it (if you want to see what this was look up `multitrigger` in the history).
