### ISSUE TITLE
Allow plans to accept lazy iterables of detectors

### ISSUE THREAD

**Issue by callumforrester** [bluesky/bluesky#1613]
Most plans in `plans.py` currently accept lists or tuples.

## Expected Behaviour
For example, you should be able to pass

```python
detectors = [det1, det2]
generator = (detector for detector in detectors)
RE(count(generator))
```

## Current Behavior
This will run but all detectors will be absent from the event documents. You have to pass a concrete list or tuple such as
```python
RE(count(detectors))
```

## Possible Solution
Some of the plans consume the generator more than once, which is why they behave oddly. One solution is to make sure all plans call

```python
detectors = list(detectors)
```
Or similar at the start.

**Comment by tacaswell** [comment]
Seems reasonable.

**Comment by callumforrester** [comment]
Reviewers: @tacaswell @callumforrester

**Comment by tacaswell** [comment]
Changing my mind (as discussed on the hackathon call) this opens up something dangerous

```
def my_plan():
   generator = (detector for detector in detectors)
   # would do the right thing
   yield from count(generator)
   # would do a very wrong thing!
   yield from count(generator)
```

Instead of making sure the plans refuse to take generators / only take `Sequence` types.
