### ISSUE TITLE
Scroll to top button and left handedness

### ISSUE THREAD

**Issue by lyonsj** [bluesky/bluesky#1624]
Might just be me but here's what happens:

I'm happily scrolling, phone in my left hand, big fat thumb working in the left third of the bottom half of my screen. I hit the scroll to top button and lose control of the app and context and it's just annoying. I didn't realise what I was doing as it was covered by my thumb.

This is a little niche I know but as I never accidently hit the button to compose I never accidently lose control. 

I'd rather just have home alert me to new things and hit that to go to the top of my feed.

**Comment by prjemian** [comment]
Might be just me. Bet you are talking about a social media app with the same name as this work. If so, you need to keep looking.

**Comment by lyonsj** [comment]
Me and my smooth brain!
