### ISSUE TITLE
Preprocessors behave unexpectedly with async logic/ophyd-async devices

### ISSUE THREAD

**Issue by rosesyrett** [bluesky/bluesky#1625]
As part of Diamond's I22-Tomo project, I have been trying to debug an issue we have seen with blueapi, where if we try to run a bp.count plan via blueapi with a ophyd-async device the run engine seems to hang on a 'wait' message. I have now discovered that the reason why it hangs is a fundamental problem with the way the run engine processes sequences/generators of messages, which is only cropping up now because we have async stage/trigger methods on detectors that don't block when they get called by the run engine.

## Minimal reproducible example

It is quite hard to write a minimal example of this issue that works, so I am going to preface this by saying, this example will only work if run inside Diamond's network, specifically to access the d11 detector for our test beamline, p38. Regardless the main points can still be demonstrated here:

```python
from bluesky.run_engine import RunEngine
from ophyd_async.core import DeviceCollector, StaticDirectoryProvider
from dodal.devices.areadetector.adaravis import SumHDFAravisDetector
from bluesky.plans as bp

RE = RunEngine()

with DeviceCollector():
    d11_det = SumHDFAravisDetector("BL38P-DI-DCAM-03", directory_provider=StaticDirectoryProvider("/some/path/a/hdf/plugin/can/write/to", "tmp"))
    
def with_yield_from():
    yield from bp.count([d11_det], num=1)

def with_loop():
    plan = bp.count([d11_det], num=1)
    for msg in plan:
        yield msg

RE(with_yield_from()) # will pass
RE(with_loop()) # will hang forever
```

listing both of these plans (i.e. `list(with_yield_from())`, `list(with_loop())`  ) reveals that the messages produced by both are exactly the same. However, running the plan which loops through the messages in an existing plan before yielding them seems to fail.

I know why this is happening on the ophyd-async side, but not why it is happening on the bluesky side. On the ophyd-async front, a `SumHDFAravisDetector` inherits it's stage and trigger methods from it's parent class (a `StandardDetector`) and look like this:

```python
    @AsyncStatus.wrap
    async def stage(self) -> None:
        """Disarm the detector, stop filewriting, and open file for writing."""
        await self.check_config_sigs()
        await asyncio.gather(self.writer.close(), self.controller.disarm())
        self._describe = await self.writer.open()

    @AsyncStatus.wrap
    async def trigger(self) -> None:
        """Arm the detector and wait for it to finish."""
        indices_written = await self.writer.get_indices_written()
        written_status = await self.controller.arm(DetectorTrigger.internal, num=1)
        await written_status
        await self.writer.wait_for_index(indices_written + 1)
```

For some reason, running `RE(with_yield_from())` means the `stage` method completes before the `trigger`, whereas running `RE(with_loop())` means it doesn't. In the latter case, `await self.writer.wait_for_index(indices_written + 1)` in the `trigger` method happens before `await self.writer.open()` in the `stage` method. `self.writer.open()` actually starts the capture of the hdf plugin, whereas `self.writer.wait_for_index` waits for it to begin. This is a race condition that should not happen, because the `stage` method should always finish before the `trigger` method begins.

Using some logging, what seems to happen is that if we use `with_loop()`, a `Msg("stage")` is sent correctly, and the detector does begin to stage, however at some point before `stage` finishes a `Msg("trigger")` is sent and `trigger` begins preemptively. 

This issue also occurs with existing pre-processors, e.g `RE(bpp.print_summary_wrapper(with_yield_from()))` will also hang.

## Expected Behavior
I expect `stage` to `finish` before trigger gets to go. I expect this behaviour should not change if we add preprocessors.

## Current Behavior
Adding a pre-processor somehow means when the run engine receives a message to stage, it doesn't wait for it to complete before processing the next message (e.g. a trigger)

## Your Environment
The above example requires the following:
1. ophyd_async from the main branch
2. dodal from the directory_provider branch
3. bluesky from main branch
4. Connection to Diamond network, specifically to p38's network.

**Comment by tacaswell** [comment]
Those two plans are not equivalent, while items that come out of the generator are the same, the other communication channels are severed with the for-loop version (see https://tacaswell.github.io/coroutines-i.html for my explanation and https://peps.python.org/pep-0380/ for why `yield from` was added to the language (particularly ~40 line block of code that actually reproduces `yield from`).

In the loop version the left hand side of the `a = yield Msg(...)` or `a = yield from plan(...)` is _always_ `None`.  I don't have a good theory why this is breaking async-ophyd in this way, but this is why `plan_mutator` is as complex as it is.

`bpp.print_summary_wrapper` is indeed broken, that is my mistake.

**Comment by rosesyrett** [comment]
Ok, so effectively the run engine uses generators as coroutines.
For the moment the solution for my team has been to scale down complexity to meet our deadline which is unfortunately almost upon us. However I am interested in how, eventually, we would be able to get something like this to work. We initially tried to write a pre-processor that would make a call to a service when it received a "start_run" message, but for the reasons mentioned above we found it did not work in practise and had to just hard code some things instead for now. Here is an example of the approach we tried with our pre-processor: https://github.com/DiamondLightSource/blueapi/blob/42cac054a299e27f0156cab38a98064d2910643d/src/blueapi/preprocessors/attach_metadata.py

What is the difference between async syntax, and using generators as coroutines? My understanding is they are essentially the same; if so, should we modify the run engine code so it uses the (newer, perhaps better understood) async keywords instead? I imagine this could be tricky r.e. ophyd objects, but there are ways to run synchronous functions inside async code that seem easy enough to implement. Or is this the eventual goal of developing ophyd-async, that we will (eventually) phase out ophyd, deprecate it, and have bluesky rewritten to use async syntax?

Thanks

**Comment by tacaswell** [comment]
If you want to trigger some side-effect as a Msg goes by I would use `plan_mutator` with a function that always just returns the `Msg`, but you can have what ever side effect you want.

> Ok, so effectively the run engine uses generators as coroutines.

Yes, RE makes full use generator-coroutines.  It is how we make things like adaptive demo on the home page work :)

I think there is value in having the Msg-like generator-corutines and the async-like coroutines.
