### ISSUE TITLE
no stop document ^C after  a previous ^C and typing `RE.stop()` or `RE.abort()`

### ISSUE THREAD

**Issue by ambarb** [bluesky/bluesky#1626]
If `^C` is issued by the user after `RE.stop()` or `RE.abort()`, bluesky does not respond.  This may happen because the user made a mistake and should have typed `RE.hault()` or simply thought they could stop every thing from moving for convenience (probably a habit of users of another common DAQ software).

Whether the users should or should not do this for convenience is probably not a topic for discussion here.  What is important to note is that pressing `^C` many times seems to break the `RE` and the terminal freezes.  Once this happens, one needs to exit the session in order to kill the process, and as a consequence, the stop document is never written to the database.

## Expected Behavior
stop document gets written to the database after pressing `Enter` for `RE.stop()` ,  `RE.abort()` or `RE.hault()`?  I don't see anything else in the stop document that happens after this, but an expert should confirm this (or others with more advanced usage that is beyond out-of-the-box bluesky)

## Current Behavior
stop document gets written to the database after as soon as possible (not waiting on motors to return to the position dictated by underlying plan code for exceptions since this doesn't seem to be a critical part of the stop document

## Possible Solution
see expected behavior, but any solution anyone one dreams of is ok by me.

## Steps to Reproduce (for bugs)
see above

## Context
see above

## Your Environment
`{'bluesky': '1.8.3.post1+g34931bb9', 'ophyd': '1.6.4'}` on RHEL8

**Comment by tacaswell** [comment]
There are two issues here:

 1. a bug in `msg_mutator` (used by `rel_scan` to make the target positions relative) that #1627 fixes)
 2. interrupting interruption cleanup is currently broken.  That is a bigger set of changes that probably requires adding another set of states to the RE state machine.  We should open a second issue for that.
