### ISSUE TITLE
Investigate flaky test `test_unrewindable_det_suspend`

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky#1633]
As @evalott100 noted in #1631 we seem to have a flaky test:

```
test_run_engine.py::test_unrewindable_det_suspend[False-test_plan-motor0-det0-msg_seq0]
```

**Comment by evalott100** [comment]
It was during [this job](
https://github.com/bluesky/bluesky/actions/runs/6773999783/job/18410110459#step:9:1771), seems to be quite a rare failure.

**Comment by stan-dot** [comment]
following @evalott100 's link

> The logs for this run have expired and are no longer available.

and the test just passed for me.

should we close this @danielballan ?

**Comment by evalott100** [comment]
Hmmm it does seem like this problem hasn't appeared in any recent runs. Happy to call this stale.
