### ISSUE TITLE
Hidden `xray-vision` dependency is still not dealt with anywhere

### ISSUE THREAD

**Issue by flowln** [bluesky/bluesky#1636]
There's still a [`xray-vision`](https://pypi.org/project/xray-vision/) hidden dependency [in the LiveImage callback](https://github.com/bluesky/bluesky/blob/9b0d72953cae867d8312cde3da2ed9cc4caf0788/bluesky/callbacks/broker.py#L80), mentioned in previous issues (https://github.com/bluesky/bluesky/issues/371 https://github.com/bluesky/bluesky/issues/823). This dependency is not mentioned anywhere in the `README`, the docs, or the requirements, so you only encounter it if you're reading the code, or if you happily stumble upon a nice `ImportError` on your bluesky journey :slightly_smiling_face: 

## Expected Behavior
No error should be raised on normal operation, if you install a package directly from where it is made available oficially.

## Possible Solution
1. Vendor-in the relevant code from `xray-vision` into Bluesky.
2. Add the `xray-vision` dependency to the project requirements (possibly optional, like the `matplotlib` dependency, though it should not make the callback accessible when it is not installed).

**Comment by callumforrester** [comment]
Reviewers: @tacaswell (who thinks vendoring in is the better path)

**Comment by tacaswell** [comment]
The abstract layers were a bit of architecture astronaut exercise.  We only ever ended up with one actual implementation so in the same move we should also squash down what ever it is we are inheriting.

**Comment by stan-dot** [comment]
The `mpl_package` supports three kinds of display: CrossSection, Stack1d and Contour. We only use the first one. Should all the others be deleted?
@tacaswell

**Comment by tacaswell** [comment]
I would phrase it as "only port what we need", but yes.

**Comment by stan-dot** [comment]
closing in favor of #1754
