### ISSUE TITLE
Add "prepare" protocol to the RunEngine

### ISSUE THREAD

**Issue by rosesyrett** [bluesky/bluesky#1637]
## Expected Behavior
A new protocol should be added to the run engine, such that if a "prepare" command is called to the run engine, the run engine
tries to call `obj.prepare` and checks that the object is `Flyable`. It should be similar to set.

## Context
At the moment, running fly-scanning in ophyd-async requires:
1. A flyer object to be defined, which holds all the detectors that will be triggered e.g. by a panda, and how those triggers will be produced (i.e. the trigger logic)
2. The flyer object to be 'set' so that the triggers are primed for the flyscan to start.

After some discussion, it's been decided that instead of using the (overloaded) `set` verb, there should be a new protocol, `prepare`, which ought to be called instead.

**Comment by coretl** [comment]
I believe this is what we discussed with @danielballan and @tacaswell, but I think there were possibilities of using it with `Triggerable` as well as `Flyable`, so I suggest we make a new standalone protocol called `Preparable` to hook this to
