### ISSUE TITLE
RunBundler open_run and close_run should be incorporated into it's constructor/destructor.

### ISSUE THREAD

**Issue by rosesyrett** [bluesky/bluesky#1642]
At the moment, there is occasional bits of code duplication between:
1. The `RunEngine` checking that `self._run_bundlers` contains the `run_key` provided by a given message, and
2. The associated `RunBundler` method checking if `self.run_is_open` is set to True.

Here is an example:

```python
class RunEngine:
    ...
    async def _collect(self, msg):

        run_key = msg.run
        try:
            current_run = self._run_bundlers[run_key]
        except KeyError as ke:
            raise IllegalMessageSequence("A 'collect' message was sent but no "
                                         "run is open.") from ke

        return (await current_run.collect(msg))
```
Then, when `current_run.collect` is awaited it calls this method:
```python
class RunBundler:
    ...
    async def collect(self, msg):
       ....
        if not self.run_is_open:
            # sanity check -- 'kickoff' should catch this and make this
            # code path impossible
            raise IllegalMessageSequence(
                "A 'collect' message was sent but no run is open."
            )
```

It seems like the `RunBundler` is never used in a state when `self.run_is_open` is set to False. Therefore, I think to reduce complexity we should move `RunBundler.open_run` into the` __init__` (or at least call it there, and make it a private method) and call `close_run` in the destructor, also making that private.

This could make a fair bit of logic in the `RunEngine` neater, i.e. opening and closing the run no longer needs direct calls to `open_run` and `close_run`; just to make and delete the dictionary key currently in `self._run_bundlers`.

**Comment by tacaswell** [comment]
It is not safe to rely on the timing of exactly when `__del__` will run (the GC can delay things longer than you expect (and the exact details are going to change with the free threading work landing in upstream)) so it is not safe to rely on that for generate the stop document (we want to be very sure it will come out exactly when we ask for it).

Given that we need to keep `close_run`, that means we can have these things in invalid states so we can not drop the logic in the bundler (but it might be worth pulling that check up into a decorator?).  We might not need independent state though and can look at the state of something else we need to track for functional reasons.

I'm mixed on do the open run on `__init__`, it has some different error handling implications (you can plausibly recover from a failure in a method call, if you fail in `__init__` you do not get the (partially) inited object back).

It is currently true that in our (nominally bug free) usage of `RunBundler` we never use it wrong, but I think there is value in the slightly defensive programming to make sure if we do put bugs in in the future that uses things out-of-order we get good error messages at the point of error rather that doing things like emitting two stop documents and getting the error someplace way downstream!

**Comment by rosesyrett** [comment]
That's a good point... I hadn't considered that you can't really rely on when garbage collection happens in python. That certainly makes my idea of putting `open_run` and `close_run` in constructors/destructors less clean!

Ultimately, I just want to avoid the code duplication we see in the example I gave above. This was one way I thought would be a nice workaround. The only other thing I can think of is making the RunBundler a context manager, but this would be a huge change to the RunEngine and probably not bring any tangible benefit. This is a small code-cleanup issue and I'm happy to drop it if you feel it's not really worth the effort.

**Comment by tacaswell** [comment]
I am going to close this, I think the side-effects are not worth the minor gain.
