### ISSUE TITLE
Add branch protections to master

### ISSUE THREAD

**Issue by rosesyrett** [bluesky/bluesky#1645]
I've got a couple of PRs open for minor changes and have just realised, I am apparently able to merge them in without any approvals and with tests failing. This should probably change for future, especially if a hackathon could be in the works.

**Comment by tacaswell** [comment]
We should also rename master -> main.

I can:
 - rename master -> main
 - change to require 1 approval to merge to main

if there is no protest.

**Comment by tacaswell** [comment]
Done!
