### ISSUE TITLE
Replace all try/except blocks that are used for logic parsing wherever easy/possible in the RunEngine

### ISSUE THREAD

**Issue by rosesyrett** [bluesky/bluesky#1646]
In general it seems most people (from the NSLS-II, Diamond collaboration meetings) are in agreement that try/except blocks shouldn't be used for parsing logic. I understand sometimes it's inevitable and actually useful to use try/except blocks in this way (especially when it relates to handling exceptions with generators and passing exceptions around). However there are a lot of relatively simple use cases where try/except could be replaced with if/else for example, and it would improve the readability of the codebase.

## Current Behavior
We have instances of try/except being used in a few places where it's probably not the best tool to use. For example, often try/except is used to catch KeyErrors:

```python
        try:
            current_run = self._run_bundlers[run_key]
        except KeyError as ke:
            raise IllegalMessageSequence(...)
```
This sort of pattern is found almost everywhere. Instead, why not replace it with:
```python
        current_run = self._run_bundlers.get(run_key)
        if not run_key:
            raise IllegalMessageSequence(...)
```

Another obvious place where this would improve readability is in `RunEngine._unsubscribe`:
```python
    async def _unsubscribe(self, msg):
        ...
        _, obj, args, kwargs, _ = msg
        try:
            token = kwargs['token']
        except KeyError:
            token, = args
        ...
```

Should be replaced with:

```python
    async def _unsubscribe(self, msg):
        ...
        _, obj, args, kwargs, _ = msg
        token = kwargs.get("token", args[0])
```

There's probably a lot more examples of this sort of thing, but these were the easiest I could find.

**Comment by tacaswell** [comment]
I am ambivalent to this.  

It does shorten the code a bit, but it lifts error checking that Python was doing for us up to our code (that is if we break the try-execpt `__getitem__` still raises `KeyError` and will still fail (but with a less-good error message/type) but if we are using `get` we can drop the return value checking and end up with `None` breaking in weird ways farther down the line).  There may have also been a performance argument to dropping try/except, but recent Python versions have made them much cheaper (free?).

I'm not sure the second example is correct.  I think it will fail if `len(args) == 0` (as the default value to `get` is evaluated before `get` is called) and will accept (but drop on the floor) any additional args past the first one.  Something like:

```python
In [4]: def test(args, kwargs):
   ...:     if (token := kwargs.get('token')) is None:
   ...:         token, = args
   ...:     return token
   ...:
```

is probably a better replacement.  

While typing this out, I suspect many of these would be good candidates for `:=` ?  I think it hits both sets of concerns ("do not use try except" and "do not let error validation get de-coupled").

**Comment by CoePaul** [comment]
Question (possibly for @tacaswell)...
In the code snippet above - where the walrus operator version of a solution is introduced - 
the args are used (is - since it's singular) the arg is used as a fallback.

Is there ever an appropriate time to check if arg(s) is None?

I first stumble into this question for the _unsubscribe method of run_engine - since one of the earlier comments on this ticket suggests that method is a good candidate for this replacement exercise.  I tried to find precedent by checking for invocations of _unsubscribe but my grep search suggests there aren't any calls.  

So I wonder if the args being None should be caught in these replacements or allowed to propagate?
