### ISSUE TITLE
Promote DeprecationWarning to UserWarning so people will see it

### ISSUE THREAD

**Issue by coretl** [bluesky/bluesky#1650]
At the moment no-one sees this warning apart from in tests:
https://github.com/bluesky/bluesky/blob/0943efdc9ba8ecff9b5c59cb0f5a38d7bb8ef1c3/bluesky/utils/__init__.py#L1810

Promote it to a UserWarning so people see it

**Comment by callumforrester** [comment]
Reviewers: @jwlodek
