### ISSUE TITLE
Add main module and version CLI

### ISSUE THREAD

**Issue by coretl** [bluesky/bluesky#1667]
We would like a similar structure to [the template on which bluesky's layout is based](https://github.com/DiamondLightSource/python-copier-template).

## Expected Behavior
`python -m bluesky --version` outputs the currently installed version of bluesky. 

## Possible Solution
Mimic the copier template linked above, adding a `__main__.py` that prints the current version when run. Also add a test that ensures it keeps working, similar to this one https://github.com/DiamondLightSource/python-copier-template/blob/main/template/tests/test_cli.py.jinja.

## Context

_Originally posted by @callumforrester in https://github.com/bluesky/bluesky/pull/1664#discussion_r1530567471_

**Comment by callumforrester** [comment]
Reviewers: @coretl @mrakitin
