### ISSUE TITLE
Dependencies: Super State Machine - not maintained

### ISSUE THREAD

**Issue by stan-dot** [bluesky/bluesky#1679]
Last update to the Super State Machine [repository](https://github.com/beregond/super_state_machine) took place 7 years ago. 

There already happened a [discussion in 2017](https://github.com/bluesky/bluesky/issues/723#issuecomment-320517555) to refactor it out of bluesky.

## Expected Behavior
We use dependencies with good maintenance status.

## Current Behavior
Bluesky imports a not-maintained module.

## Possible Solution
Refactor out the super state machine

**Comment by tacaswell** [comment]
short-term we should vendor a copy of that library into bluesky so we can drop the dependency.

medium-to-long term we should either right our own state machine or find a replacement.  This is primarily used to keep track of the state of the RE so we need to be very careful about any changes to it.

**Comment by stan-dot** [comment]
vendoring seems to match was has been already discussed before. this issue could focus on that.

for the longer view a quick search reveals libraries: 
- [fgmacedo/python-statemachine](https://github.com/fgmacedo/python-statemachine)  with 635 stars, 
- [pytransitions](https://github.com/pytransitions/transitions) with 5.3 k stars
- [p-org/P](https://github.com/p-org/P) state machine focused programming language - 2.9k stars
- [mriehl/fysom](https://github.com/mriehl/fysom) with 385 stars
- [statesman](https://github.com/opsani/statesman) with 50 stars.
that's the top of the google search so it's highly unlikely we could find something better. Of course it's at the core so care needs to be taken. Do you think this issue fits the hackathon theme well @tacaswell ? or too fragile of a system element? Maybe still some investigation would be harmless?

Just a quick check in other languages - same situation, finite state machines seem to be a niche use case.
- [looplab/fsm](https://github.com/looplab/fsm?tab=readme-ov-file) finite - state - machine in golang - so that we know it's not just Python
- [stonecypher/jssm](https://github.com/StoneCypher/jssm) 296 stars
- [xstate in the javascript ecosystem](https://github.com/statelyai/xstate) hasn't proven that successful

**Comment by danielballan** [comment]
Agreed with the above. And I will add that our usage is pretty simple, so we might consider just using implementing something simple with dictionaries. Caproto has something like this and it works well.

**Comment by clintonroy** [comment]
I've dabbled with automat, spun out of twisted https://github.com/glyph/automat

**Comment by genematx** [comment]
Here's the [PR](https://github.com/bluesky/bluesky/pull/1708) for this issue. @stan-dot, @tacaswell, could you please have a look?

**Comment by callumforrester** [comment]
Fixed by #1708
