### ISSUE TITLE
Dependencies: Pims -  not used anywhere(?)

### ISSUE THREAD

**Issue by stan-dot** [bluesky/bluesky#1680]
Possibly this was imported with the copier template transition, but the pims package [respository](https://github.com/soft-matter/pims/tree/main?tab=readme-ov-file) is not imported in any file. I could be deleted.

## Current Behavior
Unused package in `pyproject.toml`

## Possible Solution
To remove the package.

**Comment by tacaswell** [comment]
It looks like bluesky never actually dependend on it, but we used it in some of the handlers.  It looks like in came in via 4cabba36218e55a9e970727f8a1372c1253f26d6 as a CI install and then over time that migrated into the requirements files and then into pyproject.toml

It should definitely go.

**Comment by callumforrester** [comment]
Reviewers: @tacaswell
