### ISSUE TITLE
Coverage on Landing Page says "Unknown"

### ISSUE THREAD

**Issue by callumforrester** [bluesky/bluesky#1687]
## Expected Behavior
Coverage on the README landing page: https://github.com/bluesky/bluesky should reflect data from https://app.codecov.io/gh/bluesky/bluesky (currently about 88%)

## Current Behavior
![image](https://github.com/bluesky/bluesky/assets/29771545/d360b37b-a4c6-4497-b7a8-0e898e1b15ec)

## Possible Solution
Start by investigating links in the README

## Steps to Reproduce (for bugs)
Open https://github.com/bluesky/bluesky

**Comment by Villtord** [comment]
Seems to be self-cured?
![Screenshot_2024-04-15-22-25-25-29_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/bluesky/bluesky/assets/10887440/1ba82fcf-b6af-4914-9abc-ea33393250a8)

**Comment by tacaswell** [comment]
The risks of dynamic badges 🤷🏻 .
