### ISSUE TITLE
Refactor bluesky/utils/__init__.py into component modules

### ISSUE THREAD

**Issue by prjemian** [bluesky/bluesky#1723]
With PR #1709,  `bluesky/utils/__init__.py` is approaching 2,000 lines with dozens of classes and functions at the module level.  It is time to refactor this file into its component modules

_Originally posted by @prjemian in https://github.com/bluesky/bluesky/issues/1709#issuecomment-2061444739_

**Comment by prjemian** [comment]
For example, this will make it easier for me to find the code that provides the [`Msg()`](https://github.com/bluesky/bluesky/blob/a054fab2e3432534a3bebdee906f162eccb0cfe8/src/bluesky/utils/__init__.py#L66) objects.

**Comment by callumforrester** [comment]
Duplicate of #1677
