### ISSUE TITLE
unhelpful ValueError associated with positioner movement

### ISSUE THREAD

**Issue by bruceravel** [bluesky/bluesky#1768]
Just now, I accidentally did this:
```
RE(mv(xafs_y, 173.439, xafs_y, 64.63))
```
(Note, I specified the same motor twice.)

The stack trace ended with this:
```
ValueError: Can not compose overlapping cycles
```

Now, I know what a cycler is, but approximately 0% of the users of my beamline will know what a cycler is.  The likelihood that that error message would result in a phone call rather than the user figuring out the problem themself seems VERY high.   An error message with an actionable hint would be of value.

**Comment by bruceravel** [comment]
Thanks, Tom.  Certainly should have been a bluesky issue.  Sorry for the poor github skillz.

**Comment by bruceravel** [comment]
Should I close this and reopen over there?

**Comment by jwlodek** [comment]
I believe the merged PR in the cycler repository should address this issue. Can it be closed?
