### ISSUE TITLE
`LiveTable` callback doesn't work with ophyd-async object

### ISSUE THREAD

**Issue by Tom-Willemsen** [bluesky/bluesky#1772]
The `LiveTable` callback crashes if an `ophyd-async` device/signal is passed into it (it works fine with string names, just not with the actual object)

@coretl - as discussed briefly earlier

## Expected Behavior

Expected similar behaviour to an `ophyd` signal:

```python
>>> from ophyd.signal import SignalRO
>>> from bluesky.run_engine import RunEngine
>>> from bluesky.callbacks import LiveTable
>>> import bluesky.plan_stubs as bps
>>>
>>> dev = SignalRO(name="blah")
>>> RE = RunEngine()
>>>
>>> RE(bps.null(), LiveTable([dev]))
()
```

## Current Behavior

With an `ophyd-async` signal:

```python
>>> from bluesky.run_engine import RunEngine
>>> from bluesky.callbacks import LiveTable
>>> from ophyd_async.epics.signal import epics_signal_r
>>> import bluesky.plan_stubs as bps
>>>
>>> dev = epics_signal_r(float, "blah")
>>> RE = RunEngine()
>>>
>>> RE(bps.null(), LiveTable([dev]))
Traceback (most recent call last):
  File "c:\Instrument\dev\bluesky\tmp\.venv\Lib\site-packages\bluesky\callbacks\core.py", line 200, in get_obj_fields
    field_list = sorted(field.describe().keys())
                        ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'keys'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Instrument\dev\bluesky\tmp\.venv\Lib\site-packages\bluesky\callbacks\core.py", line 311, in __init__
    self._fields = get_obj_fields(fields)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Instrument\dev\bluesky\tmp\.venv\Lib\site-packages\bluesky\callbacks\core.py", line 202, in get_obj_fields
    raise ValueError(  # noqa: B904
ValueError: Fields must be strings or objects with a 'describe' method that return a dict.
```

## Possible Solution

Might just need wrapping in `maybe_await` or similar?

## Steps to Reproduce (for bugs)

See above

## Context

`LiveTable` is useful for debugging. Workaround: pass the signal name as a string rather than the device itself.

This is the `ophyd-async` equivalent of the example in the docs [here](https://nsls-ii.github.io/bluesky/callbacks.html#interactively).

## Your Environment

```
Python 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)] on win32
```

**Comment by tacaswell** [comment]
I forgot that you could pass objects to `LiveTable` and have it sort it self out!  The quickest fix is to pass a list of strings instead.

You don't need the RE etc, I expect that

```python
>>> from ophyd.signal import SignalRO
>>> from bluesky.callbacks import LiveTable
>>>
>>> dev = SignalRO(name="blah")
>>>
>>> LiveTable([dev])
```

is sufficient to cause the crash (because the error is happening in the `__init__` of `LiveTable` which must be complete before we call `RE` at all.  Given when this happens (before we go into the RE loop) I'm not sure that there is a way that we can make the async functions work as the sync functions do .

Can someone remind me why `describe` needs to do IO (in ophyd-sync we currently do this because we are doing type-sniffing of the value that comes back...but we can/should stop doing that) ?

**Comment by coretl** [comment]
> Can someone remind me why `describe` needs to do IO (in ophyd-sync we currently do this because we are doing type-sniffing of the value that comes back...but we can/should stop doing that) ?

https://github.com/bluesky/ophyd-async/blob/8273a2e0980fc586db38abb15fc6d354e0d40e68/src/ophyd_async/epics/signal/_aioca.py#L306-L308

We get the metadata (like enum choices, limits, units) every time describe is called. We considered caching this at connect, but then we would need to add a method to drop the cache, and as the RE already caches describe it seemed better to ask CA/PVA every time

**Comment by tacaswell** [comment]
So I think our option are:

 - accept ophyd-async does not support the "make a live table for this object" code path
 - find a way to detect that `describe()` is an async function and spin an event loop enough to let it run

-----

I feel this issue should now only be worked on by people named "Tom" as we are at 3/3.

**Comment by Tom-Willemsen** [comment]
Maybe we just adjust the docs to no longer _recommend_ passing in a device object to `LiveTable`, but without necessarily preventing it for existing users?

I do think what's written in the user docs - especially in the tutorial sections - should generally work for both `ophyd` and `ophyd-async` devices - but maybe I'm being too idealistic...

**Comment by tacaswell** [comment]
it may also be good to catch this error and provide a better error message, but I am :+1: on adjusting the docs and calling it a good.

-----

Thinking a bit broader, all we really need for the names of the columns not the full describe and probably the hints.  Do we want a guaranteed sync protocol to get them? In all cases can we get at least the keys without doing I/O? Do we have any other use case for "just-the-keys-and-hints" than a short-hand API on LiveTable?

**Comment by coretl** [comment]
Do you need all the keys, or is just the hints enough? If keys, could we add a new category of hint and put it there?

**Comment by tacaswell** [comment]
You need all the keys for sensible fallback if there are no hints (show everything).
