### ISSUE TITLE
bps.wait move_on kwarg is undocumented

### ISSUE THREAD

**Issue by DiamondJoseph** [bluesky/bluesky#1824]
This behaviour, added as part of #1641, is undocumented. According to @coretl it is to enable a `wait` that times out to not be an exception. In my opinion, it's not the best name as "wait" and "move on" are antonyms. It should be documented or self-documenting what the argument does.
If the kwarg name was amended to "allow_timeout" or similar, it might be clearer what is meant.

https://github.com/bluesky/bluesky/blob/3bce96b85558993499174be7eebcd09f270a9271/src/bluesky/plan_stubs.py#L636

**Comment by DominicOram** [comment]
> It should be documented or self-documenting what the argument does.

I feel that for something as user facing as a plan stub it should have a docstring entry regardless of whether we feel the name is clear

**Comment by coretl** [comment]
Discussion between @danielballan, @evalott100, @coretl suggests we keep the `wait` planstub making the `wait` message, but change `move_on=False` to `error_on_timeout=True`
