### ISSUE TITLE
Fix linter on CI

### ISSUE THREAD

**Issue by tacaswell** [bluesky/bluesky#1834]
It appears that an update to ruff has become much stricter about using `tuple` vs `Tuple` (and other built in classes).  We need to:

 - run ruff over the code base and mass-migrate to the new scheme (assuming py39 supports generics on the built in classes)
 - tell ruff to ignore those checks

**Comment by coretl** [comment]
- [python3.9](https://docs.python.org/3.9/library/typing.html#typing.Tuple) is where `tuple[int]` is first supported
- ruff [UP006](https://docs.astral.sh/ruff/rules/non-pep585-annotation/) is the rule that checks this
- it uses `python-version` in `pyproject.toml` to determine this

**Comment by callumforrester** [comment]
I vote for mass-migrate (happy to do it)
