### ISSUE TITLE
return in finally swallows exceptions

### ISSUE THREAD

**Issue by iritkatriel** [bluesky/bluesky#1838]
In https://github.com/bluesky/bluesky/blob/a40a025aef605174bc44980254c3a1ea8f95bfc9/src/bluesky/run_engine.py#L1117 and https://github.com/bluesky/bluesky/blob/a40a025aef605174bc44980254c3a1ea8f95bfc9/src/bluesky/run_engine.py#L1119 there is a return statement in a finally block, which would swallow any in-flight exception.

This means that if an unhandled exception is raised in the try block (including a `BaseException` other than `KeyboardInterrupt`) or an exception is raise in an `except` block (as is explicitly done in the `except Exception` block), this exception would not propagate as expected.

See also https://docs.python.org/3/tutorial/errors.html#defining-clean-up-actions.

**Comment by tacaswell** [comment]
Thank you for flagging this!  I have a PR in to fix it.  Fortunately I think that this is far enough down the sad-path that it is unlikely to have been hit is practice.

I am curious what drew your attention?

**Comment by iritkatriel** [comment]
> I am curious what drew your attention?

I'm doing some analysis on how people use/abuse return in finally, so running static analysis on open source code. I report problems when I see them.
