### ISSUE TITLE
Add to home screen as PWA severely breaks site on iOS

### ISSUE THREAD

**Issue by waynesbrain** [bluesky/bluesky#1846]
## Expected Behavior

- Add to home screen on iPhone.
- Launch BlueSky from home screen icon.
- BlueSky should open as a standalone PWA.

## Current Behavior

- Add to home screen on iPhone.
- Launch BlueSky from home screen icon.
- The Bsky.app url opens in the Safari browser where it freezes until I quit the browser.
- Removing the home screen bookmark fixes the problem.

## Possible Solution

- Set your manifest to standalone, do not open in Safari.

## Steps to Reproduce (for bugs)

1. Add to home screen on iPhone.
2. Launch BlueSky from home screen icon.

## Context

The PWA mode for X works perfectly. I am trying to accomplish an escape from the tyranny of the Apple app store as much as is possible, without switching to an ad-company owned phone.

## Your Environment

- iPhone 11
- iOS 18.1
- Safari

**Comment by tacaswell** [comment]
This is the wrong bluesky (we are https://blueskyproject.io).

**Comment by waynesbrain** [comment]
Wow sorry! What a colossal misunderstanding. For some reason "An Experiment Specification & Orchestration Engine" just flew right over my head and I was like "Okay, that's like their social graph thing or whatever" :rofl:

**Comment by tacaswell** [comment]
I mean, from a certain point of view social media is a big social experiment....
