### ISSUE TITLE
Re-emit StreamResources when a StreamDatum is emitted against one from an old RunStart

### ISSUE THREAD

**Issue by coretl** [bluesky/bluesky#1849]
## Use cases
At the moment we have 3 possible ways of doing multiple flyscans in an experiment

### 1. One run, One file
For example, 3 identical gridscans at different energies
```
Stage
RunStart
  Prepare(dets, 3 x gridscans) & Prepare(motors, gridscan1) & Set(energy, energy1)
  Kickoff(dets, motors)
  Collect(dets) until Complete(motors)
  Prepare(motors, gridscan2) & Set(energy, energy2) & Complete(dets)
  Kickoff(dets, motors)
  Collect(dets) until Complete(motors)
  Prepare(motors, gridscan3) & Set(energy, energy3) & Complete(dets)
  Kickoff(dets, motors)
  Collect(dets) until Complete(motors) & Complete(dets)
RunStop
Unstage
```
### 2. Different runs, Different files
For example, 3 different gridscans in different files
```
Stage
RunStart
  Prepare(dets, gridscan1) & Prepare(motors, gridscan1)
  Kickoff(dets, motors)
  Collect(dets) until Complete(motors) & Complete(dets)
RunStop
RunStart
  Prepare(dets, gridscan2) & Prepare(motors, gridscan2)
  Kickoff(dets, motors)
  Collect(dets) until Complete(motors) & Complete(dets)
RunStop
RunStart
  Prepare(dets, gridscan3) & Prepare(motors, gridscan3)
  Kickoff(dets, motors)
  Collect(dets) until Complete(motors) & Complete(dets)
RunStop
Unstage
```
### 3. Different runs, One file
For example, 3 different gridscans in the same file
```
Stage
RunStart
  Prepare(dets, gridscan1 + gridscan2 + gridscan3) & Prepare(motors, gridscan1)
  Kickoff(dets, motors)
  Collect(dets) until Complete(motors)
RunStop
RunStart
  Prepare(motors, gridscan2) & Complete(dets)
  Kickoff(dets, motors)
  Collect(dets) until Complete(motors)
RunStop
RunStart
  Prepare(motors, gridscan3) & Complete(dets)
  Kickoff(dets, motors)
  Collect(dets) until Complete(motors) & Complete(dets)
RunStop
Unstage
```

## Current Behavior
1 and 2 work fine, 3 will produce StreamResource documents during grdscan1, then StreamDatums against them during gridscan2 and 3

## Expected Behavior
A copy of the gridscan1 StreamResources emitted with different ids during gridscan2 and gridscan3, and any StreamDatums retargeted to point at them.

## Possible Solution
Pass in a cache of previously emitted StreamResources to the bundler, distinct from the StreamResources we have already emitted, and if we see a StreamDatum against one then copy it, change the id, emit and store it, and modify the StreamDatum to point at it before emitting it

**Comment by coretl** [comment]
@DiamondJoseph please can you check this makes sense

**Comment by coretl** [comment]
@DominicOram which usecases from the above to MX need?

**Comment by DiamondJoseph** [comment]
Makes sense, when can we let go of a cached StreamResource: when the detector is unstaged?

**Comment by jwlodek** [comment]
Maybe on writer.close()? Since its

**Comment by jwlodek** [comment]
Sorry didn't mean to close, on my phone and my keyboard suddenly disappeared and pressed the close button on accident

**Comment by coretl** [comment]
> Makes sense, when can we let go of a cached StreamResource: when the detector is unstaged?

The cache is in the RunEngine / bundler, as that is the only thing that knows about runs. I think on unstage of the detector is probably the best hook we have...

**Comment by tacaswell** [comment]
I have some concerns that this will hide cases when this is unintentional. 

For detectors that want to do this, could we have them "re-arm" sending the StreamResource when it is prepared and let the bundler drop identical versions of it?

**Comment by DiamondJoseph** [comment]
Dom is on holiday until at least late January, so my understanding of the MX use case (to have it written down) is to prevent re-arming their detector when running repeated collections with the same detector settings. Arm detector for N*M frames, collect M frames for each of N samples without having to wait for N*arming_period.

**Comment by DiamondJoseph** [comment]
Nameless colleague with initials CF had some confusion over the issue, so I made this diagram to make it clearer what the current behaviour is
![blueapi excalidraw](https://github.com/user-attachments/assets/49d37e4d-8fc2-4e51-9a5e-087c094b1126)

**Comment by callumforrester** [comment]
> @DiamondJoseph please can you check this makes sense

@coretl while I'm not Joseph, it took me a minute (and his help) to get my head around this issue because you're not "re-emitting" a stream resource document (which to me implies unchanged, verbatim) but emitting a brand new document that just happens to refer to the same file.

**Comment by DiamondJoseph** [comment]
When does an ophyd (non-async) device emit a (non-Stream) Resource? Just checking if this may also be an issue there- where Resources are tied directly to the StartDocument.

**Comment by coretl** [comment]
> I have some concerns that this will hide cases when this is unintentional.
> 
> For detectors that want to do this, could we have them "re-arm" sending the StreamResource when it is prepared and let the bundler drop identical versions of it?

The issue is that we do not want to `unstage` or re-`prepare` the detector, as this re-arms the detector which is slow for Eiger. If we could do that we would just use case 2. The only difference between case 2 and 3 is when the `open_run` message is sent, and we don't have a verb to communicate that down to the device. I guess a possibility would be to make this explicit by adding an argument to `collect_asset_docs(index, new_run)` that it could use to emit a new StreamResource pointing to the same file. I guess we would have to examine function signatures to know whether to send that argument for back compat.

> it took me a minute (and his help) to get my head around this issue because you're not "re-emitting" a stream resource document (which to me implies unchanged, verbatim) but emitting a brand new document that just happens to refer to the same file.

Good point, I've updated the title to reflect this

**Comment by tacaswell** [comment]
right, my proposal is to make the detectors that need to do this to have the behavior of prepare that does _stuff_ the first time it is called after a `stage` and just re-queues the `StreamResource` to be collected.

This puts the "specialness" in the detector not the plan.

**Comment by DominicOram** [comment]
> [@DominicOram](https://github.com/DominicOram) which usecases from the above to MX need?

As discussed with @coretl and @DiamondJoseph our usecase is 1, 2 and 3. In particular for 3 we have a sample pin that holds N  samples, with different metadata for each. To increase throughput we want to do one arm of the detector then collect at the N different locations to produce one underlying file. However at each location we would like to emit the different metadata to produce N records in LIMS.

**Comment by coretl** [comment]
> right, my proposal is to make the detectors that need to do this to have the behavior of prepare that does _stuff_ the first time it is called after a `stage` and just re-queues the `StreamResource` to be collected.

To elaborate, from the detector's point of view, for use case 1 it sees:
```
stage()
prepare(3 x grid scans)
kickoff()
collect_asset_docs() while not complete()
kickoff()
collect_asset_docs() while not complete()
kickoff()
collect_asset_docs() while not complete()
unstage()
```
For use case 3 it sees exactly the same. This means there is no existing verb we can use to tell it the difference between use case 1 (emit stream_resource once) and use case 3 (emit stream_resource 3 times).

The options I can see:
- Choose at init time whether the detector should emit 1 or 3 stream_resources in the above sequence (stops you supporting both use case 1 and use case 3 in the same detector)
- Choose at prepare time whether the detector should emit 1 or 3 stream_resources in the above sequence (requires plan that runs prepare to know if it is preparing for use case 1 or 3)
- Optionally allow `collect_asset_docs(index, run_start)` where we pass in the run start id, which we be called if the signature of the function takes `run_start`. This allows us to switch between use case 1 or 3 just by emitting a new `RunStart` document.

@tacaswell @DiamondJoseph @DominicOram thoughts?

**Comment by tacaswell** [comment]
Can we do `collect_asset_docs(index, include_resource=False)` instead? I worry about leaking too much information down causing extra-tight coupling.

**Comment by coretl** [comment]
@evalott100 pointed out that if it is being used in multiple runs, then we will be calling `describe` or `describe_collect` as part of the new run, so we could use that as the trigger that a new resource needs emitting rather than `collect_asset_docs`. Would that work?

**Comment by tacaswell** [comment]
I don't think we have a hard requirement that you _must_ call describe before collecting the docs so I'm a bit wary of relying on that (see the (re-)discovery that ophyd AD needs `trigger` to be called before `describe`).

**Comment by coretl** [comment]
I think it is already a hard requirement, when we `collect_asset_docs` we emit `stream_datum` with a reference to `descriptor`. This must have come from `describe()`. As it's already built into the document hierarchy, is there anything to stop us depending on it in ophyd-async?

**Comment by DiamondJoseph** [comment]
I thought the device created Partials without the Run or Doc UUID, which were filled in by the RunBundler?

**Comment by coretl** [comment]
Decided to attempt a cross-bundler cache of stream resources, use that uid as an internal ref only, then rewrite the ids on the way out

**Comment by coretl** [comment]
@danielballan this means we will **always** change the id of the stream resource, is that a reasonable thing to do?
