### ISSUE TITLE
Should bluesky set the ipython loop runner?

### ISSUE THREAD

**Issue by coretl** [bluesky/bluesky#1855]
At present if you do `await coro` in ipython, it will schedule the coro in its own event loop, run until complete, then stop the event loop until the next `await` command. This works fine until you try and do something with signals, when there are tricky details of channel caches to get right. We can make `await` use the bluesky event loop by doing:

```python
from bluesky.run_engine import call_in_bluesky_event_loop
from IPython import get_ipython
get_ipython().loop_runner = call_in_bluesky_event_loop
```

Should we do this:
- In bluesky, in ophyd-async or in user code?
- On import or on call of a function?

@tacaswell thoughts?

**Comment by tacaswell** [comment]
My knee-jerk reaction is:

 - in bluesky
 - require explicit function call to enable

**Comment by jwlodek** [comment]
> My knee-jerk reaction is:
> 
>     * in bluesky
> 
>     * require explicit function call to enable

This would be my preference as well. Function in `bluesky.utils` that user calls at the start of their ipython profile.
