### ISSUE TITLE
issue with fixed-acquisition count cameras + pause/suspenders

### ISSUE THREAD

**Issue by tacaswell** [bluesky/bluesky#408]
This was reported at SRX due to suspenders, but I assume will also apply at HXN and anyplace else that is collecting multiple _events_ worth of data into a single file (if HXN ever does software controlled raster scans).

The problematic sequence of events is:
- ...
- open
- trigger (but advance the count in AD as the camera has been triggered)
- PAUSE
- {discard}
- resume (but do not roll back the AD counters)
- open
- trigger
- read (the data in this event is the re-taken data)
- save
- ...
- open
- trigger (this is the last trigger that get saved into the file)
- read
- close
- open
- trigger (AD seems to happily poke the tigger bit, but not data is saved to file as it is closed)
- read (bogus information gets inserted into FS)
- close

I think the simplest solution is to have suspenders (optionally) use soft-pause (pro: minimally disruptive con: users of suspenders should put in _lots_ of checkpoints, and clear checkpoints before triggering because these things are not always safe to replay over if AD is involved).

Other solutions 
- turning all pauses inside of an open/save block into 'quasi-soft' which are deffered to end of block (pro: ?, con: yet more complexity and special cases in RE, plays badly with _long_ waits, will not work for `trigger; wait; open; read; save`)
- sort out how to roll-back AD frame counters (pro: does not add any complexity to user con: expect this to be fiendishly complex on the RE side to keep track of what/how to roll things back.  Will need to deal with `checkpoint; trigger; open; read; PAUSE; trigger; open; read; save` which is a case that would need to be re-wound, but the object does not know enough to take care of it's self so it has to live on the RE side, something like: `cp; trigger; open; read; PAUSE;  untrigger(??!?); trigger; open; read; save)
- always pad out fixed length data streams by a few percent (pro: simple! con: will not always work? does not work with quasi-structural data (directly filling NxMxE cube) )

**Comment by tacaswell** [comment]
Addressed by #486

**Comment by danielballan** [comment]
Have you closed the loop on actually using #486 at SRX? Is this issue closable?

**Comment by tacaswell** [comment]
No, they are busy running users and have a work-around on the analysis side.

**Comment by danielballan** [comment]
Stale, closing.
