### ISSUE TITLE
Allow olog callback access to documents other than start

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky#478]
Particularly, Yugang wants exposure_time, acquire_time, etc. from detector configuration.

**Comment by klauer** [comment]
We need some standardized way to keep an olog entry open/appendable during a run - you wouldn't want the detector configuration in a separate log entry than the runstart.

**Comment by hhslepicka** [comment]
Why not generate the entry at the end with all the needed information including the exit status of the scan?

**Comment by klauer** [comment]
That's probably what @danielballan is aiming to do. My desire for the appendable solution is that runstart and runstop may be many hours inbetween depending on the beamline, and it'd be nice to see the initial information as soon as possible.

**Comment by danielballan** [comment]
@klauer we are on the same page

Get Outlook for iOS<https://aka.ms/o0ukef>




On Thu, Jun 2, 2016 at 2:49 PM -0700, "K Lauer" <notifications@github.com<mailto:notifications@github.com>> wrote:


That's probably what @danielballan<https://github.com/danielballan> is aiming to do. My desire for the appendable solution is that runstart and runstop may be many hours inbetween depending on the beamline, and it'd be nice to see the initial information as soon as possible.

**Comment by danielballan** [comment]
Can anyone volunteer to work on this? I don't know how editing olog entries works.

**Comment by danielballan** [comment]
@shroffk Can you give us a hand with this? What's missing is a simple example of how to *edit* (specifically, append to) an olog entry that was recently created.

**Comment by danielballan** [comment]
cc @yugangzhang

**Comment by shroffk** [comment]
Implemented the prototype for log entry update
https://github.com/Olog/pyOlog/tree/update-log

example usage
```
text = 'test update python log entry ' + datetime.now().isoformat(' ')
        updatedLogEntry = LogEntry(text=text,
                           owner='testOwner',
                           logbooks=[self.testLogbook])
        updatedLog = self.client.update(log.getId(), updatedLogEntry)
```

**Comment by tacaswell** [comment]
I turned that branch into a PR https://github.com/NSLS-II/pyOlog/pull/3 but it does not merge cleanly.

**Comment by danielballan** [comment]
This is supported in pyOlog now, but the olog callbacks built into bluesky don't integrate it with out of the box (yet).

**Comment by mrakitin** [comment]
I like the idea.

**Comment by danielballan** [comment]
Yes, it would be nice to make this happen. This work should probably be done in a new suitcase package (suitcase-olog) now.

**Comment by danielballan** [comment]
We plan to address this in suitcase-olog with pyolog2.

**Comment by CJ-Wright** [comment]
See: https://github.com/bluesky/suitcase-core/issues/69
