### ISSUE TITLE
Replace 'checkpoint' Msg with checkpoint kwarg on Msg

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky#537]
Avoid this situation, where the user wanted to mark the 'whatever' Msg as a safe point to roll back to, but was interrupted before the 'checkpoint' Msg could be processed.

```
Msg('whatever')
Ctrl+C
Msg('checkpoint')
```

Instead, allow this:

```
Msg('whatever', checkpoint=True)
```

Since message processing is granular -- plans can never be externally interrupted mid-Msg -- the checkpoint can be guaranteed to be processed.

**Comment by klauer** [comment]
Is interpreting/popping off kwargs globally from all `Msg`s a good pattern? I'm not sure I have a strong opinion either way.

**Comment by danielballan** [comment]
Yes, it's worth noticing that `checkpoint` could potentially collide with a kwarg in a user-defined coroutine. At this point in the development, I think it's OK to declare a reserved kwarg in Msg.

And, contrary to what the title of this issue suggests, I think we would also continue to support `Msg('checkpoint')` forever.

**Comment by klauer** [comment]
A point for it: less messages to express the same thing

A point against it: less messages to express the same thing - now anyone (or any code) looking at the list of messages has to be aware of the newly reserved kwargs

**Comment by tacaswell** [comment]
There is something to be said for making the checkpoints atomic with the operation as well.

**Comment by danielballan** [comment]
Agreed that losing the clear `Msg('checkpoint')` in the list of messages would be a step backward.

**Comment by danielballan** [comment]
Closing as stale.
