### ISSUE TITLE
Document rationale for which commands return status objects

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky#589]
Specifically document why stage, configure, and unstage do not.

**Comment by tacaswell** [comment]
Despite my verbal arguments, I am starting to doubt the current behavior.  

It seems reasonable to stage multiple devices in parallel, which means we need to be able to return a status object from them :disappointed: .

**Comment by danielballan** [comment]
We can't stage devices in parallel. When a given device is done staging, it reports back to the RunEngine any other (sub)devices it has staged as part of its staging process. The plans take this feedback into account to avoid redundantly staging things. Thus, staging has to be done is series.

This should never get to "expensive," time-wise because staging is generally expected to be done once per plan (less-than-or-equal-to once per run) and generally expected to be fast configuration PV-flipping. Anything lengthy motor-moving should be done through set.

**Comment by danielballan** [comment]
This is an ophyd documentation issue and should be done as part of future ophyd documentation work. It is currently explained in "Anatomy of a Device" in the bluesky tutorial.

> Specifically document why stage, configure, and unstage do not.

Also, note that we plan to make stage and unstage return status objects.
