### ISSUE TITLE
add 'wait_for_any' plan + RE methods

### ISSUE THREAD

**Issue by tacaswell** [bluesky/bluesky#622]
```python
def wait_for_any(groups: List[str]) -> str:
```

takes list of group names, returns the name of the first one to be finished.

**Comment by danielballan** [comment]
Just curious -- have you found a use case? This reminds me a little bit of "OR" on status objects, which we discarded because we couldn't think of a use case.

**Comment by tacaswell** [comment]
Automatic mixing of plans

```python
def mixed_plan():
    plans = {'a': plan_stack_a, 'b': plan_stack_b}
    wait_fors = []
    for plns in plans.item():
        n = yield from plns.pop()
        wait_fors.append(n)
   while len(wait_fors):
        next = yield from wait_for_any(wait_fors)
        wait_fors.remove(next)
        n = yield from plans[next].pop()
        if n:
            wait_fors.append(n)
```

The plans should probably return the group to wait for to indicate that they are done. 


@cmazzoli asked for this bit of complexity :smiling_imp:

**Comment by danielballan** [comment]
Closing as stale
