### ISSUE TITLE
elliptical spiral and fermat spiral scans

### ISSUE THREAD

**Issue by awalter-bnl** [bluesky/bluesky#648]
Can we add the ability for step sizes to be different in the x and y direction (elliptical rather than circular) in spiral and fermat_spiral scans?

**Comment by danielballan** [comment]
Do you have any interest in writing it, starting from the source code of the existing spiral scans?

**Comment by danielballan** [comment]
^ That's an honest question. It's not out of the question that someone in DAMA could do this, but doing it yourself will probably make it happen faster. And when we merge it into bluesky you can say you have code in bluesky. 😈

**Comment by awalter-bnl** [comment]
Thats a question of timing, I already wrote a “square spiral” plan based on the spiral plan. It is really for me just a mater of time, Let me start on this and see how far I can get with the time I have available.

cheers
Andrew



On Feb 24, 2017, at 5:12 PM, Dan Allan <notifications@github.com<mailto:notifications@github.com>> wrote:


^ That's an honest question. It's not out of the question that someone in DAMA could do this, but doing it yourself will probably make it happen faster. And when we merge it into bluesky you can say you have code in bluesky. 😈

**Comment by awalter-bnl** [comment]
This is pretty old, but should be a quick turnaround for me. So I plan to take a look today.

**Comment by awalter-bnl** [comment]
actually just went to look at how to implement this and found that it has been implemented already in the `plan_patterns` for both. I will update the ``plans`` with the new ``dy=None`` kwarg that allows a different delta in the y direction compared to the x and it is done.

**Comment by awalter-bnl** [comment]
PR # 1260 will resolve this issue
