### ISSUE TITLE
Support for versions of Python

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky#699]
This issue is to track the discussion of how quickly we should drop support for Python 3.5 in order to use the nice features of 3.6, and more broadly how quickly we intend to drop support for old versions of 3.x as new ones are released. @hhslepicka brought this up over Hangouts, and I will here recap our conversation.

Reminder of current situation: The data acquisition stack (ophyd, bluesky, their dependencies) support Python 3.5+. The data retrieval stack (databroker and its dependencies) supports Python 2.7 and Python 3.4+.

We all seem to have consensus that databroker should continue to support Python 2.7 at least until 2020 when Python 2.7 stops getting security updates. Databroker should do this in order to interface with legacy analysis software that is not actively supported anymore.

But it's an open question how rapidly bluesky/ophyd should drop support for 3.5 in order to use nice features of 3.6 (and so, into the future). Of course, "migrating" from 3.5 to 3.6 is not at all the same as migrating from 2.7 to 3.x because API breakages between 3.x versions are rare and slow. In practice, forcing users to upgrade from 3.5 to 3.6 is only a burden on packaging; it does not require changes to user code. Nonetheless, as @hhslepicka correctly flagged, the impression that we are rapidly dropping support for old releases of Python 3.x might leave users wary. How should we balance these concerns?

Python 3.5 brought us async/await syntax, which is why we dropped 3.4. Python 3.6 has been touted as an especially big step forward for the language in general. (Both Fernando and Raymond have said something along the lines of, "It's the first Python 3 release that justifies the pain.") I would advocate for:

* guiding our collaborators to target 3.6 for their deployments
* supporting 3.5 for the next release or two
* dropping 3.5 support by bluesky 1.0
* sustaining long-term support for Python 3.6 through the bluesky 1.x release cycle

**Comment by stuartcampbell** [comment]
I agree with @hhslepicka we do need to be mindful of having a constant (and never ending) version churn.  We already have the reputation for constant changes, we don't want to add to the perception. 😄 

Also, I would say a 👍 to maintaining Python 2.7 support for `databroker`, the more APIs that we have for different languages and versions will only enable more folks to use it! 🥇

**Comment by prjemian** [comment]
Use of milestones, spaced at regular or irregular intervals, can help

**Comment by tacaswell** [comment]
:+1: to @danielballan 's timeline (modulo not many more releases before 1.0).

Long term, I think we should strive for "last 2 minor releases of python" which gives each version of python about a 2 year window and only drop support for a version of python in a minor or major release (depending on how long we plan to support at the patch level which I would argue should be only until the next minor given the size, speed of development, and current installed base of the software).

also :+1: to maintaining 2.7 support for the data retrieval side for at least another 2 years.

**Comment by danielballan** [comment]
Update on our roadmap and plan for support of Python versions:

Bluesky 1.0 and ophyd 1.0 will be tagged by November 1. We're thinking that bluesky 1.0 and ophyd 1.0 will support Python 3.5 and Python 3.6, but that future releases in 1.x may drop Python 3.5 support. Python 3.6 will have long-term support in future 1.x releases. Do you think that will be satisfactory, @hhslepicka? This is still very much negotiable. Python 3.6 has some great new features that we'd like to use, but we don't want to alienate our new collaborators!

Databroker 1.0 will not be tagged this year, as it is still in a less mature stage of development. To reiterate the consensus above, the data _retrieval_ software including databroker and its dependencies will support Python 2.7 (as well as 3.x, of course) until at least 2020.

Once 1.0 is tagged, we will write a clear roadmap into our documentation.

**Comment by prjemian** [comment]
Ok with py3.6 only for bluesky and ophyd [we will upgrade to 3.6 this week here at APS]
Agree with "& py2.7" for databroker as most of our users are using that now

**Comment by teddyrendahl** [comment]
Don't think it will be an issue here at SLAC

**Comment by hhslepicka** [comment]
Ok with 3.5 & 3.6 for 1.0 & 3.6 only after that and also agree for py2.7 for data broker. Looks pretty good to me. Thank you @danielballan

**Comment by tacaswell** [comment]
We never got arround to dropping support for python 3.5 and are currently having issues getting the tests to pass on py3.7 (due to odd zmq issue see #1063 ).  Punting to next release.

**Comment by CJ-Wright** [comment]
I think you did drop support for python 3.5. The script for the zmq proxy has f-strings.

**Comment by prjemian** [comment]
If you have not yet dropped suport for Py3.5, please consider keeping Py3.5 support since anaconda has no support for 3.6+ on the raspberry pi.  Lowly as it is, it's a great demo box (and can even run EPICS 7 and synApps 6).  The native Raspbian OS provides Py3.4.

**Comment by danielballan** [comment]
Recall that ophyd lost its 3.5 support in https://github.com/NSLS-II/ophyd/pull/642 with signoff from all facilities involved.

@prjemian Have you come across https://github.com/jjhelmus/berryconda? The creator is a former Argonne employee, now full-time Anaconda maintainer, and a friend of ours. I think it's a bit of a hobby project, but it looks like it's still being actively maintained.

(For what it's worth, I personally just _build_ Python 3.6, but it takes about an hour on an RPi Zero, and I haven't attempt the heavy numerical libraries yet. At that point I'm sure berryconda would be well worth it.)

**Comment by CJ-Wright** [comment]
As a sidenote conda-forge is actively pursuing arm builds https://github.com/conda-forge/conda-forge.github.io/issues/269 you might consider weighing in on that issue if that could help you.

**Comment by prjemian** [comment]
I own part of that signoff, for sure.  These links are news for me.  Don't recognize that former Argonnenaut.

**Comment by prjemian** [comment]
This [chart](https://github.com/jjhelmus/berryconda/graphs/code-frequency) shows major activity on this project just this past fall.

**Comment by danielballan** [comment]
Numpy now provides guidance for scientific Python projects on this: https://numpy.org/neps/nep-0029-deprecation_policy.html.
