### ISSUE TITLE
Separate callbacks into a separate Python package

### ISSUE THREAD

**Issue by CJ-Wright** [bluesky/bluesky#723]
We may consider cleaving callbacks from bluesky in the general sense. Callbacks are useful outside the context of data acquisition (I personally feel that any data analysis system down stream should support them).

## Expected Behavior
Callbacks are their own library

## Current Behavior
They are not their own library

## Possible Solution
Make a new library

## Context
I'm writing a data analysis workflow and would like to use callbacks but don't want the RunEngine (as pretty and nice as it is @tacaswell) or the other acquisition logic.

**Comment by CJ-Wright** [comment]
Expanded from #719

**Comment by danielballan** [comment]
@stuartcampbell, @tacaswell, and I discussed this over lunch on Friday, and I'll summarize here.

Separating callbacks from the rest of the package has a certain attractive purity. The callbacks are useful without the RunEngine and the plans. The RunEngine and plans aren't so useful without at least _some_ callbacks available to test and/or use, so it seems like a separate callbacks package would become a required dependency of bluesky.

Given that there would be a one-way dependency, what's the practical advantage of separating the packages? Is it helpful to be able to install the callbacks without the RunEngine and the plans? Notice that the RunEninge and the plans don't add heavy dependencies. Specifically, looking at requirements.txt:

```
cycler
event-model
historydict
jsonschema
matplotlib
numpy
super_state_machine  # not heavily used, may be factored out in the future
toolz
traitlets  # will be removed in the upcoming release
```

All of the dependencies are small, pure Python packages that are cheap and easy to install, except for the ones that a callbacks package would need anyway (numpy, matplotlib).

**Comment by danielballan** [comment]
This will happen organically as new work on things that consume documents happen in separate repos.
