### ISSUE TITLE
Look at stealing Lutz's Peak Stats work.

### ISSUE THREAD

**Issue by stuartcampbell** [bluesky/bluesky#758]
Sounds like Lutz has done a better version of the peakstats function - we should steal it.

**Comment by danielballan** [comment]
@lwiegart Where should look to find this code? Is it somewhere on GitHub, like in chxtools? If you can post a link at your convenience, I'll start the process of integrating it with bluesky.

**Comment by lwiegart** [comment]
It's very likely not on github (unless Yugang put it there :-) ). Let me check tomorrow, I am out today. L
________________________________

**Comment by danielballan** [comment]
@lwiegart Is this it? https://github.com/NSLS-II-CHX/ipython_ophyd/blob/d2389af73506d6cf2f70e95a336b77a16267381f/profile_collection/startup/95-utilities.py#L209

**Comment by lwiegart** [comment]
Yes, 98% sure :-)
________________________________

**Comment by danielballan** [comment]
We'll take those odds! Thanks.

**Comment by mrakitin** [comment]
I think it's the function. I even recognize my [part](https://github.com/mrakitin/SRW/blob/master/env/work/srw_python/uti_math.py#L615) of the code there regarding the FWHM calculation (can possibly be improved, currently only linear interpolation between points is supported, please see `fwhm_scipy()` below in that module).

**Comment by danielballan** [comment]
Great. Thanks for chiming in, @mrakitin.

**Comment by licode** [comment]
I compared the algorithm in current bs and the one from CHX and summarize them as below.

Common part:

Both of the algorithms find the crossing points between a middle line ((np.max(y) + np.min(y)) / 2) and the experimental data y. Once those two crossing points are found, calculation of center, fwhm and center of mass is performed.

Different part:

The algorithm in bs also considers linear background removal before peak statistics calculation as an option. 

CHX algorithm considers a different case when experimental data y looks like a step function. In this scenario, the algorithm applies error function to fit the data to get all the statistics, like cen, fwhm.

I think it is good idea to add the step function part from CHX algorithm into our current code. Any comment or suggestion?

**Comment by danielballan** [comment]
Interesting. My impression from @lwiegart was that CHX also did a better job fitting _peaks_ correctly. I'd like to clear that up. Lutz -- is the issue you had with our built-in PeakStats that it does a bad job with peaks or that it does a bad job with step functions?

**Comment by lwiegart** [comment]
It -for obvious reasons- did no job at all for step functions and at least the version I tried a long time ago produced centers in >50% of the cases that were pretty apparently in the woods. Not sure if that was the same algorithm that is used now - we gave up on the built-in version after initial tests showed that it was borderline useless.
L
________________________________

**Comment by danielballan** [comment]
@lwiegart Thanks. Agreed that we would not expect it to work on step functions.

@licode Regarding peak-finding, it your assessment that the linear background is the only difference between CHX's implemention and bluesky's? If so, can you look at the history of the file to see how out implementation has been improved? I'd like to account for the behavior Lutz is reporting if we can, because I remember him reporting it at the time, though there's a limit to what we can do without a concrete example of a failure.

**Comment by licode** [comment]
center of mass was improved before, but fwhm and cen keep the same.

https://github.com/NSLS-II/bluesky/commits/master/bluesky/callbacks/scientific.py

**Comment by danielballan** [comment]
I think center of mass was not improved; I think it was just vendored (copied directly into the source code) to avoid depending on scipy for only one simple Python+numpy function. Is that right?

Also, notice that the oldest commit is titled "MNT: Reorganize callbacks modules into callbacks package," and that is shows [the relevant file being renamed](https://github.com/NSLS-II/bluesky/commit/c9d9c4b16315b95e1a795571dcd8e4d3d8389de1#diff-3c92cd0747bb03180732d2d835069f70). To trace history further back in time, see [the original file's history](https://github.com/NSLS-II/bluesky/commits/v0.3.2/bluesky/scientific_callbacks.py) as well.

Regarding edge/step-finding -- which could be addressed in a separate PR from this one -- you should also refer to [Tom's abandoned attempt to incorporate that](https://github.com/NSLS-II/bluesky/pull/501) and compare it to Lutz's work.

**Comment by danielballan** [comment]
@lwiegart One more question -- Would you point us to a couple real scans in CHX's database (I imagine they would be dscans...) that would serve as good test cases? If you can give us the uids, we can look them up and get the data ourselves.

**Comment by stuwilkins** [comment]
Just to chime in, but usually I just differentiate the data to find the inflection point of a step function, this way the other _peak stats_ work. Just my 2 cents..... Could you have an option to diff() the data then send it into the same algorithm?

**Comment by danielballan** [comment]
I like that suggestion.

**Comment by licode** [comment]
I like the idea to do derivative on step function.

**Comment by licode** [comment]
Those two methods are basically the same after some correction on fwhm.  https://github.com/NSLS-II/bluesky/pull/888

**Comment by lwiegart** [comment]
peak(diff) will find the largest gradient in the data, which is not necessarily the step one is looking for, in particular in the case of noisy data. Just my 50 cents, no objections to options or anything else you would like to do.
Dan, I don't have time to dig through logbooks and find datasets for testing. Is there a way you can deploy this without updating/breaking anything else? If so, I would be happy to just test it under real conditions for a while. As we're currently not using the build-in peak stats but our own module, there should be no harm: it either works or we continue to use ours.
________________________________

**Comment by danielballan** [comment]
@lwiegart Fair enough. Li's tests show that bluesky's PeakStats now produce results identical to yours on noisy data, so that gives me enough confidence to put this on the floor and see how it goes.

**Comment by tacaswell** [comment]
closed by https://github.com/bluesky/bluesky/pull/888/files
