### ISSUE TITLE
BUG: `RemoteDispatcher` requires two starts after stop

### ISSUE THREAD

**Issue by CJ-Wright** [bluesky/bluesky#809]
So I start up the `RemoteDispatcher` for ZMQ then stop it with a `KeyboardInterrupt` and then I need to run the `start` method twice before it properly starts. I assume that this is unintended?

**Comment by danielballan** [comment]
Like the proxy, it is not meant to be reused. If you are interested, I would merge a PR adding a ratchet that makes it impossible restart, as I did for the Proxy. (Look for `self.closed`.)

**Comment by CJ-Wright** [comment]
Hmm ok. I'll look into putting together a PR.
