### ISSUE TITLE
Make %wa recursive.

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky#828]
The `wh_pos()` function in ophyd, which was removed from ophyd in ophyd v0.7.0 and "replaced" by the `%wa` magic in bluesky v0.10.0, would accept compound devices and recursively find the positioners inside them. I failed to replicate this feature in `%wa`, partly because I can't think of a very clean way to do it. This is wrapped up in my own confusion about how to think about multi-axis positioners, something we need to clear up conceptually before 1.0. Anyway, elegance aside, BL staff have requested we restore this feature, and we should include it in v0.10.1.

**Comment by ambarb** [comment]
@danielballan %wa will fail on things with multiple read attributes (i.e. `%wa [m3a]`). Is this the same thing you mentioned here, or is this something to note as a difference from `wh_pos()`?

**Comment by danielballan** [comment]
Yep, same problem.

**Comment by tacaswell** [comment]
We think this addressed by labels in ophyd.
