### ISSUE TITLE
Build a library of QtWidgets to support a bluesky GUI

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky#834]
We do not plan to ship a bluesky GUI, but we do plan to ship QtWidgets that would make it easy to quickly build for one some specific purpose.

**Comment by tacaswell** [comment]
I think part of this is going to be annotating all of the 'standard' plans.

**Comment by danielballan** [comment]
This is https://github.com/bluesky/bluesky-browser and https://github.com/bluesky/bluesky-ui
