### ISSUE TITLE
Consider using zict instead of HistoryDict.

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky#924]
We should consider using `c` in [this zict example](https://zict.readthedocs.io/en/latest/#example) instead of `HistoryDict` as the default `RE.md`. It backs each entry in the dict with a separate file, thus avoiding the sqlite locking issue that prevents multiple `RE` instances from referring to the same `md`.

**Comment by tacaswell** [comment]
If we do this, also update the recommended way to do this in docs.
