### ISSUE TITLE
implement 'golden section search' to find local maximum

### ISSUE THREAD

**Issue by tacaswell** [bluesky/bluesky#925]
Hoisted from https://github.com/NSLS-II/bluesky/pull/920#issuecomment-345819631

See https://en.wikipedia.org/wiki/Golden-section_search

**Comment by tacaswell** [comment]
We can revive this if anyone asks about it.

**Comment by teddyrendahl** [comment]
https://github.com/pcdshub/nabs/blob/a1f56d054ebc507edad1d6cb506b09de2878bb25/nabs/optimize.py#L144

**Comment by tacaswell** [comment]
@teddyrendahl We should come up with a better way to advertise the existence of such plans....
