### ISSUE TITLE
Document 'contingency_wrapper'.

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky#979]
This is a better version of 'finalize_wrapper'. Maybe 'finalize_wrapper' should become un-documented. No reason to drop it entirely and break API, but 'contingency_wrapper' is more flexible and better.

**Comment by mrakitin** [comment]
+1 for keeping `finalize_wrapper`.

**Comment by danielballan** [comment]
Revisiting this, I think we should _not_ un-document `finalize_wrapper` unless/until we go through and update all our built-in plans to use `contingency_plan` instead. I made a separate issue for that work, #1288.
