### ISSUE TITLE
allow for different behviour of LiveTable and LivePlot in best effort callback

### ISSUE THREAD

**Issue by jrmlhermitte** [bluesky/bluesky#992]
We should allow for the different behaviour of plotting for LiveTable and LivePlot in the best effort callback.

One method suggested by @cmazzoli is that we can use 'plot_fields' and 'table_fields' as keys for the best effort callback. When they're not available, the default can be to use 'fields'

**Comment by danielballan** [comment]
The reason that we hesitated to add this layer of control in the first place is:

> ["All problems in computer science can be solved by another level of indirection...except for the problem of too many layers of indirection."](https://en.wikipedia.org/wiki/Indirection)

Add `bec.table_fields` would add one more special name to know, one more thing to check. From a design point of view, it reminds me of Python's built-in `logging` framework, with layers of filtering and control.  Inarguably, there are times when this level of granular control are useful. But I worry that, like the `logging` framework, it will become difficult to users -- especially new users -- to hold all that in their head. "Why doesn't it show up?! It's in 'table_fields'! Oh, it's not in hints...."

To avoid this confusion, I think we really ought to just pick _one_ place where this choice is made. We used to do it globally in `gs.TABLE_COLS`, very much analogous to the proposed `bec.table_fields`. Then we switched to doing it per-device via hints. The advantage of doing it per-device is that you don't need to update `table_fields` every time you use a different motor or detector. For example, if you switch from moving `theta` to moving `gamma`, the table fields automatically update without a coordinated change by the user. This seems like a win. We made this case when we first released the BestEffortCallback and retired `gs`.

Is my argument convincing, @cmazzoli? Additionally, do you find that you most often wish to _remove_ columns from the table or _add_ them?

**Comment by CJ-Wright** [comment]
@tacaswell could we reframe that as 'independent variable-like' and 'dependent variable-like' things?

**Comment by tacaswell** [comment]
We think that this will be handled by the new bluesky-browser work and the run-router work.
